import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { renderToStaticMarkup } from 'react-dom/server';
import { ComponentsPage } from './components/CatalogComponentsPage.tsx';

test('renders the component library categories and source links', () => {
  const html = renderToStaticMarkup(<ComponentsPage />);

  assert.match(html, /data-component-library="true"/);
  assert.match(html, /data-reference-component="component-card"/);
  assert.match(html, />31 components</);
  assert.match(html, /data-component-source-group="site:Melius"/);
  assert.match(html, /data-component-source-group="site:Content Architecture"/);
  assert.match(html, /data-component-source-group="site:Craft\/Wild"/);
  assert.match(html, /data-component-source-group="site:Taste Labs"/);
  assert.match(html, /data-component-source-group="site:Flim"/);
  assert.match(html, /data-component-source-group="site:Details.so"/);
  assert.match(html, />Melius<\/strong>/);
  assert.match(html, />Content Architecture<\/strong>/);
  assert.match(html, />Craft\/Wild<\/strong>/);
  assert.match(html, />Taste Labs<\/strong>/);
  assert.match(html, />Flim<\/strong>/);
  assert.match(html, />Details.so<\/strong>/);
  assert.match(html, />6 components<\/span>/);
  assert.match(html, />9 components<\/span>/);
  assert.match(html, />7 components<\/span>/);
  assert.match(html, />5 components<\/span>/);
  assert.match(html, />3 components<\/span>/);
  assert.match(html, />1 component<\/span>/);
  assert.equal(html.match(/data-component-source-group=/g)?.length, 6);
  assert.ok(html.indexOf('site:Melius') < html.indexOf('site:Content Architecture'));
  assert.ok(html.indexOf('site:Content Architecture') < html.indexOf('site:Craft/Wild'));
  assert.ok(html.indexOf('site:Craft/Wild') < html.indexOf('site:Taste Labs'));
  assert.ok(html.indexOf('site:Taste Labs') < html.indexOf('site:Flim'));
  assert.ok(html.indexOf('site:Flim') < html.indexOf('site:Details.so'));
  assert.match(html, />Button <span>2</);
  assert.match(html, />Navigation <span>2</);
  assert.doesNotMatch(html, />Header <span>/);
  assert.match(html, />Footer <span>2</);
  assert.match(html, />Card <span>3</);
  assert.match(html, />Section <span>16</);
  assert.match(html, />Media <span>1</);
  assert.match(html, />Display <span>2</);
  assert.match(html, />Effects &amp; Motion <span>3</);
  assert.doesNotMatch(html, />Input <span>/);
  assert.doesNotMatch(html, />Checkbox &amp; Toggle <span>/);
  assert.doesNotMatch(html, /Primitives|Composites/);
  assert.match(html, /data-reference-gallery-shell="components"/);
  assert.match(html, /href="\/sites\?query=Melius"/);
  assert.match(html, /href="\/sites\?query=Content%20Architecture"/);
  assert.match(html, /href="\/sites\?query=craft.wild.as"/);
  assert.match(html, /href="\/sites\?query=tastelabs.com"/);
  assert.match(html, /href="\/sites\?query=flim.ai"/);
  assert.match(html, /href="\/sites\?query=details.so"/);
  assert.match(html, /component-preview--melius-button/);
  assert.doesNotMatch(html, /component-preview--model-controls/);
  assert.match(html, /component-preview--split-button/);
  assert.equal(html.match(/data-component-preview-name=/g)?.length, 31);
  assert.doesNotMatch(html, /data-component-preview-name="AccordionContent"/);
  assert.match(html, /data-component-preview-name="MenuCard"/);
  assert.match(html, /data-live-component="SiteHeader"/);
  assert.match(html, /data-live-component="HeroSection"/);
  assert.match(html, /data-live-component="FooterEasterEgg"/);
  assert.doesNotMatch(html, /data-live-component="MeliusFooter"/);
  assert.match(html, /data-live-component="ModelWebGLCarousel"/);
  assert.match(html, /data-live-component="PersonaStack"/);
  assert.match(html, /data-component-preview-name="SpiralScene"/);
  assert.match(html, /data-live-component="AsciiShowcaseCard"/);
  assert.match(html, /data-live-component="CommonProblemsPanel"/);
  assert.match(html, /data-live-component="RepoExplorer"/);
  assert.match(html, /data-live-component="SpiralScene"/);
  assert.match(html, /data-live-component="ClosingAsciiPanel"/);
  assert.match(html, /data-live-component="TestimonialsCarousel"/);
  assert.match(html, /data-live-component="GlyphField"/);
  assert.match(html, /data-craft-wild-live-component="HeroSection"/);
  assert.match(html, /data-craft-wild-live-component="WorkCarouselSection"/);
  assert.match(html, /data-craft-wild-live-component="ProcessFlowSection"/);
  assert.match(html, /data-craft-wild-live-component="ProtocolPartsSection"/);
  assert.match(html, /data-craft-wild-live-component="ExperimentsCarouselSection"/);
  assert.match(html, /data-craft-wild-live-component="ContactSection"/);
  assert.match(html, /data-craft-wild-live-component="TetrisFooter"/);
  assert.match(html, /data-taste-labs-live-component="TasteHeroSection"/);
  assert.match(html, /data-taste-labs-live-component="TasteChallengeCarouselSection"/);
  assert.match(html, /data-taste-labs-live-component="TasteMissionSection"/);
  assert.match(html, /data-taste-labs-live-component="TasteStackSection"/);
  assert.match(html, /data-taste-labs-live-component="TasteSwipeFooter"/);
  assert.match(html, /data-flim-live-component="FlimHeroSearchSection"/);
  assert.match(html, /data-flim-live-component="FlimWhatIsFlimSection"/);
  assert.match(html, /data-flim-live-component="FlimDatabaseScrollSection"/);
  assert.match(html, /data-live-component="OverlapTransitionStage"/);
  assert.match(html, /data-component-id="details-so-overlaptransitionstage"/);
  assert.match(html, />Generate React</);
  assert.match(html, /data-flim-preview-mode="overview"/);
  assert.match(html, /data-flim-live-component="FlimDatabaseScrollSection"[^>]*style="[^"]*--flim-live-width:2114px/);
  assert.doesNotMatch(html, /catalog-preview__repo|catalog-preview__studio|catalog-preview__spiral/);
  assert.match(html, /class="ca-mobile-menu-frame"/);
  assert.match(html, /data-preview-surface="card"/);
  assert.match(html, /component-preview-viewport--card/);
  assert.match(html, /class="component-preview-root"/);
  assert.doesNotMatch(html, /catalog-preview--melius|catalog-preview--content-architecture/);
  assert.match(html, /aria-label="Menu preview viewport"/);
  assert.match(html, /data-viewport="mobile"/);
  assert.doesNotMatch(html, /data-preview-presentation="isolated"/);
  assert.match(html, /aria-label="Show mobile preview" aria-pressed="true"/);
  assert.match(html, /aria-label="Show desktop preview" aria-pressed="false"/);
  assert.match(html, /component-library-card__viewport-switcher/);
  assert.match(html, /component-library-card--wide/);
  assert.match(html, /data-preview-layout="wide"/);
  assert.match(html, /component-library-card--compact/);
  assert.match(html, /data-preview-layout="compact"/);
  assert.doesNotMatch(html, /component-library-card--standard/);
  assert.doesNotMatch(html, /data-preview-layout="standard"/);
  assert.match(html, /component-library-card--immersive/);
  assert.match(html, /data-preview-layout="immersive"/);
  assert.match(html, /data-live-component="SpiralScene"[^>]*style="[^"]*height:100%[^"]*width:100%/);
  assert.match(html, /data-preview-fit="fill"/);
  assert.match(html, /data-live-component="RepoExplorer"[^>]*style="[^"]*height:900px/);
  assert.doesNotMatch(html, /data-component-id="melius-announcementbar"/);
  assert.doesNotMatch(html, /data-component-id="melius-modelcarouselcontrols"/);
  assert.doesNotMatch(html, /data-component-id="melius-cookieconsentbanner"/);
  assert.doesNotMatch(html, /data-component-id="melius-cookiepreferencesdialog"/);
  assert.doesNotMatch(html, /data-component-id="melius-canvasscene"/);
  assert.doesNotMatch(html, /data-component-id="melius-canvasshowcase"/);
  assert.doesNotMatch(html, /data-component-id="melius-pricingsection"/);
  assert.doesNotMatch(html, /data-component-id="melius-faqsection"/);
  assert.doesNotMatch(html, /data-component-id="content-architecture-sitefooter"/);
  assert.doesNotMatch(html, /data-component-id="content-architecture-learnmoredrawer"/);
  assert.equal(html.match(/data-preview-ratio="intrinsic"/g)?.length, 25);
  assert.doesNotMatch(html, /data-component-id="content-architecture-herosection"/);
  assert.doesNotMatch(html, /data-component-id="content-architecture-pricingsection"/);
  assert.doesNotMatch(html, /data-component-id="content-architecture-app"/);
  assert.doesNotMatch(html, /data-component-id="content-architecture-studiomodelauncher"/);
  assert.doesNotMatch(html, /data-component-id="content-architecture-featuressection"/);
  assert.doesNotMatch(html, /data-component-id="content-architecture-showcasesection"/);
  assert.match(html, /data-preview-viewport="mobile"/);
  assert.match(html, /data-component-preview-name="MenuCard"/);
  assert.match(html, /aria-label="Open full Navigation component"/);
  assert.doesNotMatch(html, />DesktopMenuCard</);
  assert.doesNotMatch(html, />MobileMenuCard</);
  assert.match(html, /aria-label="Close menu"/);
  assert.match(html, /aria-expanded="true"/);
  assert.match(html, /Now available with Astro/);
  assert.match(html, />Features</);
  assert.match(html, />The Repo</);
  assert.match(html, />Showcase</);
  assert.match(html, />Pricing</);
  assert.match(html, />FAQ</);
  assert.match(html, />Blog</);
  assert.match(html, /class="melius-button/);
  assert.match(html, /class="split-button"/);
  assert.match(html, /aria-label="Get access"/);
  assert.match(html, /component-library__source-heading/);
  assert.doesNotMatch(html, /component-library__source-copy"><small>/);
  assert.doesNotMatch(html, /component-group-button/);
  assert.doesNotMatch(html, /Catalog reference/);
  assert.doesNotMatch(html, /React · CSS/);
  assert.doesNotMatch(html, /Live preview not connected/);
  assert.match(html, /data-component-source-type="site"/);
  assert.match(html, /data:image\/svg\+xml/);
  assert.match(html, /data:image\/png;base64/);
  assert.match(html, /component-library-card__logo--content-architecture/);
  assert.match(html, /component-library-card__logo--melius/);
  assert.match(html, /component-library__source-logo component-library-card__logo--taste-labs[^>]*>[\s\S]*?6a1da2ac3e6ba66f852367c6_clip\.png/);
  assert.match(html, /component-library-card__logo discovery-card__logo component-library-card__logo--taste-labs[^>]*>[\s\S]*?6a1da2ac3e6ba66f852367c6_clip\.png/);
  assert.match(html, /component-library__source-logo component-library-card__logo--flim[^>]*>[\s\S]*?695bc6699e9ebf7bc1099cbd_icon\.png/);
  assert.match(html, /component-library-card__logo discovery-card__logo component-library-card__logo--flim[^>]*>[\s\S]*?695bc6699e9ebf7bc1099cbd_icon\.png/);
  assert.doesNotMatch(html, />Action</);
  assert.doesNotMatch(html, />Site · Melius</);
  assert.doesNotMatch(html, /data-catalog-shell|data-section="components"/);
  assert.doesNotMatch(html, /Needs review|data-component-status|component-library__status/i);
});

test('preloads Taste Labs animations before mounting their players', () => {
  const preview = readFileSync(new URL('./components/TasteLabsLivePreview.tsx', import.meta.url), 'utf8');
  const mission = readFileSync(
    new URL('../../artifacts/downloads/tastelabs.com/2026-08-22-product/reverse-engineering/selected-components-suite/src/components/TasteMissionSection.jsx', import.meta.url),
    'utf8',
  );
  assert.match(preview, /animationDataCache/);
  assert.match(preview, /loadAnimationData\(animationUrl\)/);
  assert.match(mission, /animationData \? \{ data: animationData \} : \{ src: animationUrl \}/);
});

test('keeps reconstructed component styles isolated from ComponentCard chrome', () => {
  const previewCss = readFileSync(new URL('./componentLibrary.css', import.meta.url), 'utf8');
  const productTypography = readFileSync(new URL('./productTypography.css', import.meta.url), 'utf8');
  const meliusCss = readFileSync(new URL('../../artifacts/downloads/melius.com/reverse-engineering/home/react-demo/src/styles.css', import.meta.url), 'utf8');
  const meliusFooter = readFileSync(new URL('../../artifacts/downloads/melius.com/reverse-engineering/home/react-demo/src/components/MeliusFooter.jsx', import.meta.url), 'utf8');
  const catalogComponentsPage = readFileSync(new URL('./components/CatalogComponentsPage.tsx', import.meta.url), 'utf8');
  const flimLivePreview = readFileSync(new URL('./components/FlimLivePreview.tsx', import.meta.url), 'utf8');
  const flimWhatIsFlim = readFileSync(new URL('../../artifacts/downloads/flim.ai/2026-08-23-home/reverse-engineering/selected-components-suite/src/components/FlimWhatIsFlimSection.jsx', import.meta.url), 'utf8');
  const flimStyles = readFileSync(new URL('../../artifacts/downloads/flim.ai/2026-08-23-home/reverse-engineering/selected-components-suite/src/styles.css', import.meta.url), 'utf8');

  assert.match(previewCss, /\.component-preview-root\s*\{[\s\S]*?contain: layout paint style;/);
  assert.match(
    previewCss,
    /\[data-component-id='content-architecture-closingasciipanel'\] \.component-preview-viewport--card \{\s*inset: 12px;/,
  );
  assert.match(
    previewCss,
    /\[data-component-id\^='flim-'\] \.component-preview-viewport--card \{\s*inset: 12px;/,
  );
  assert.doesNotMatch(previewCss, /\.catalog-preview\s+(?:button|a|input|select)/);
  assert.match(
    productTypography,
    /:where\(button,[\s\S]*?:not\([\s\S]*?\.component-preview-root \*/,
  );
  assert.match(meliusCss, /\.melius-footer \{[^}]*font-family:ui-sans-serif, system-ui/);
  assert.match(meliusCss, /\.melius-footer__newsletter h3 \{[^}]*font-family:recklessStandard[^}]*letter-spacing:normal/);
  assert.match(meliusCss, /\.newsletter-form__control input \{[^}]*font-family:easeStandard[^}]*letter-spacing:-\.03em/);
  assert.match(meliusFooter, /<h3>Don't miss out<\/h3>/);
  assert.match(flimLivePreview, /imageUrls: \[1, 3, 2, 4\]/);
  assert.match(flimWhatIsFlim, /data-animation-phase=\{phase\}/);
  assert.match(flimLivePreview, /FlimWhatIsFlimSection: \{ width: 846, height: 1913/);
  assert.match(catalogComponentsPage, /FlimWhatIsFlimSection'\) return '846 \/ 1913'/);
  assert.match(flimStyles, /\.flim-what-is-flim__floating-image--1 \{ top: 5\.93%; left: 35%; width: 30%; \}/);
  assert.match(flimStyles, /\.flim-what-is-flim\.is-merge \.flim-what-is-flim__floating-image--1 \{ top: 62\.4%; left: 0; width: 52\.35%; \}/);
  assert.match(flimWhatIsFlim, /replayTimer = window\.setTimeout\(play,/);
  assert.doesNotMatch(flimWhatIsFlim, /previewMode === 'card'\) \{\s*setPhase\('merge'\)/);
  assert.match(flimStyles, /img\.flim-what-is-flim__platform-mobile \{[\s\S]*?display: block;/);
  assert.match(flimStyles, /\.flim-what-is-flim__platform-screen \{\s*display: none;/);
  assert.match(flimStyles, /\.flim-physics-pill \{[\s\S]*?background: var\(--flim-black\);[\s\S]*?color: var\(--flim-white\);/);
  assert.match(flimStyles, /\.flim-physics-pill\.is-orange \{[\s\S]*?background: var\(--flim-orange\);[\s\S]*?color: var\(--flim-white\);/);
  assert.match(flimStyles, /img\.flim-platform-panel__mobile \{\s*display: none;/);
});
