import { ArrowRight } from "@phosphor-icons/react";
import { SiteFooter } from "./SiteFooter.jsx";
import { SiteNavigation } from "./SiteNavigation.jsx";
import { StudioChrome } from "./StudioChrome.jsx";

const ARTICLES = [
  {
    title: "Your Site Is Invisible to AI Agents (and Your CMS Can Fix It)",
    description: "AI agents read your site as token-heavy HTML and cite it badly. Two CMS features fix it: an editor-owned llms.txt generated by AI, and per-page Markdown served to agents on the same URL.",
    meta: "28 Jun 2026 · 16 min read",
    href: "https://www.contentarchitecture.dev/blog/serve-content-to-ai-agents-llms-txt-markdown-sanity",
  },
  {
    title: "Stale Sanity Content in Next.js and Astro: The Two Caches and How to Fix Them",
    description: "Sanity content not updating in Next.js or Astro, or only showing after a redeploy? Two caches cause it: the Sanity CDN and the framework's own cache. How each one works and how to fix stale content.",
    meta: "27 Jun 2026 · 14 min read",
    href: "https://www.contentarchitecture.dev/blog/stale-sanity-content-nextjs-caching-revalidation",
  },
];

function ReadArticleLink() {
  return (
    <span className="blog-article__read">
      <span>Read article</span>
      <ArrowRight aria-hidden="true" weight="regular" />
    </span>
  );
}

function BlogArticle({ article }) {
  return (
    <li className="blog-article">
      <a href={article.href}>
        <h2>{article.title}</h2>
        <p className="blog-article__description">{article.description}</p>
        <p className="blog-article__meta">{article.meta}</p>
        <ReadArticleLink />
      </a>
    </li>
  );
}

export function BlogPage({ onNavigate }) {
  const studioChrome = { drawer: false, header: true, footer: true, minimap: true };
  const heroContent = {
    eyebrow: "Knowledge Hub",
    title: "Knowledge Hub",
    lede: "Practical, opinionated writing on content architecture.",
  };

  return (
    <div className="blog-route">
      <SiteNavigation currentKey="blog" onNavigate={onNavigate} />
      <StudioChrome
        chrome={studioChrome}
        heroContent={heroContent}
        onChangeChrome={() => {}}
        onChangeHero={() => {}}
      />
      <main className="blog-main">
        <section className="blog-section" data-page-builder-section="blogIndex">
          <div className="blog-section__inner">
            <div className="blog-intro">
              <h1>Knowledge Hub</h1>
              <div className="blog-intro__copy">
                <p>Practical, opinionated writing on <strong>content architecture</strong>, headless CMS, and shipping real products with Sanity and Next.js.</p>
                <p>Every post comes from decisions already baked into this starter: how to model content that scales, query it cleanly, and turn structure into pages search engines and AI assistants can actually read.</p>
              </div>
            </div>
            <ul className="blog-list">
              {ARTICLES.map((article) => <BlogArticle article={article} key={article.href} />)}
            </ul>
          </div>
        </section>
      </main>
      <SiteFooter onNavigate={onNavigate} />
    </div>
  );
}
