export const COMPONENT_GROUPS = [
  { id: "all", label: "All components" },
  { id: "page", label: "Page sections", description: "The large blocks that make up a complete page." },
  { id: "ui", label: "UI building blocks", description: "Buttons, cards, menus, navigation and content widgets." },
  { id: "effects", label: "Visual effects", description: "Canvas, WebGL, textures and motion treatments." },
  { id: "system", label: "Internal system", description: "Routing and authoring tools, not normal page components." },
];

export const COMPONENT_CATALOG = [
  {
    id: "app",
    name: "App",
    group: "system",
    kind: "Application",
    reuse: "Composition root",
    source: "src/App.jsx",
    description: "Owns client-side route transitions and composes the reconstructed Home and Blog pages.",
    evidence: "Route and transition behavior",
  },
  {
    id: "hero-section",
    name: "HeroSection",
    group: "page",
    kind: "Section",
    reuse: "Pattern candidate",
    source: "src/components/HeroSection.jsx",
    description: "Viewport-height opening section combining copy, CTA, status rows, a spiral scene, and scroll control.",
    evidence: "Hero DOM, layout, scroll cue",
  },
  {
    id: "problem-section",
    name: "ProblemSection",
    group: "page",
    kind: "Section",
    reuse: "Pattern candidate",
    source: "src/components/ProblemSection.jsx",
    description: "Two-column problem narrative with the diagnostic terminal treatment.",
    evidence: "Section layout and terminal state",
  },
  {
    id: "features-section",
    name: "FeaturesSection",
    group: "page",
    kind: "Section",
    reuse: "Pattern candidate",
    source: "src/components/FeaturesSection.jsx",
    description: "Long-scroll feature narrative layered over the interactive glyph field.",
    evidence: "Scroll layout and glyph behavior",
  },
  {
    id: "repo-explorer",
    name: "RepoExplorer",
    group: "ui",
    kind: "UI component",
    reuse: "Site-specific",
    source: "src/components/RepoExplorer.jsx",
    description: "Repository browser with edition switching, file tree, source panel, minimap, and terminal strip.",
    evidence: "Next.js/Astro switching and file states",
  },
  {
    id: "showcase-section",
    name: "ShowcaseSection",
    group: "page",
    kind: "Section",
    reuse: "Pattern candidate",
    source: "src/components/ShowcaseSection.jsx",
    description: "Portfolio narrative and responsive grid of ASCII reveal cards.",
    evidence: "Showcase grid and card states",
  },
  {
    id: "reviews-section",
    name: "ReviewsSection",
    group: "page",
    kind: "Section",
    reuse: "Pattern candidate",
    source: "src/components/ReviewsSection.jsx",
    description: "Customer-review carousel with image and directional navigation.",
    evidence: "Review cycling interaction",
  },
  {
    id: "pricing-section",
    name: "PricingSection",
    group: "page",
    kind: "Section",
    reuse: "Pattern candidate",
    source: "src/components/PricingSection.jsx",
    description: "Two-edition pricing comparison, animated price figures, and included-features matrix.",
    evidence: "Pricing cards and viewport entry",
  },
  {
    id: "faq-section",
    name: "FaqSection",
    group: "page",
    kind: "Section",
    reuse: "Pattern candidate",
    source: "src/components/FaqSection.jsx",
    description: "FAQ section with independently expandable accessible rows.",
    evidence: "Accordion expanded states",
  },
  {
    id: "closing-section",
    name: "ClosingSection",
    group: "page",
    kind: "Section",
    reuse: "Pattern candidate",
    source: "src/components/ClosingSection.jsx",
    description: "Closing call-to-action composed around an ASCII art field.",
    evidence: "Closing layout and visual treatment",
  },
  {
    id: "site-footer",
    name: "SiteFooter",
    group: "ui",
    kind: "Navigation",
    reuse: "Pattern candidate",
    source: "src/components/SiteFooter.jsx",
    description: "Newsletter form, contact links, animated status marker, and footer navigation.",
    evidence: "Footer controls and form state",
  },
  {
    id: "site-navigation",
    name: "SiteNavigation",
    group: "ui",
    kind: "Navigation",
    reuse: "Component candidate",
    source: "src/components/SiteNavigation.jsx",
    description: "Fixed responsive navigation that switches between the recovered desktop and mobile menu cards.",
    evidence: "Desktop/mobile navigation states",
  },
  {
    id: "blog-page",
    name: "BlogPage",
    group: "page",
    kind: "Page",
    reuse: "Page-specific",
    source: "src/components/BlogPage.jsx",
    description: "Standalone article-index route using the reconstructed navigation and footer.",
    evidence: "Blog route structure",
  },
  {
    id: "learn-more-drawer",
    name: "LearnMoreDrawer",
    group: "ui",
    kind: "Navigation",
    reuse: "Component candidate",
    source: "src/components/LearnMoreDrawer.jsx",
    description: "Floating expandable secondary navigation drawer.",
    evidence: "Drawer open and closed states",
  },
  {
    id: "studio-chrome",
    name: "StudioChrome",
    group: "system",
    kind: "Authoring",
    reuse: "Site-specific",
    source: "src/components/StudioChrome.jsx",
    description: "Authoring overlay with minimap, field selection, and movable inspection panel.",
    evidence: "Studio-mode interactions",
  },
  {
    id: "studio-section-editor",
    name: "StudioSectionEditor",
    group: "system",
    kind: "Authoring",
    reuse: "Site-specific",
    source: "src/components/StudioSectionEditor.jsx",
    description: "Schema-driven editing controls used by the Studio overlay.",
    evidence: "Field editing contract",
  },
  {
    id: "ascii-texture",
    name: "AsciiTexture",
    group: "effects",
    kind: "Visual effect",
    reuse: "Visual candidate",
    source: "src/components/AsciiTexture.jsx",
    description: "Repeated mono-text texture used as a background treatment.",
    evidence: "Background texture behavior",
  },
  {
    id: "ascii-page-transition",
    name: "AsciiPageTransition",
    group: "effects",
    kind: "Visual effect",
    reuse: "Component candidate",
    source: "src/components/AsciiPageTransition.jsx",
    description: "Canvas-based cover and reveal transition used between internal routes.",
    evidence: "Route transition phases",
  },
  {
    id: "pull-window",
    name: "PullWindow",
    group: "ui",
    kind: "Control",
    reuse: "Component candidate",
    source: "src/components/PullWindow.jsx",
    description: "Composable draggable-window foundation.",
    evidence: "Pointer drag behavior",
  },
  {
    id: "pull-window-handle",
    name: "PullWindowHandle",
    group: "ui",
    kind: "Control",
    reuse: "Component candidate",
    source: "src/components/PullWindow.jsx",
    description: "Handle companion for PullWindow drag control.",
    evidence: "Pointer drag behavior",
  },
  {
    id: "ascii-image",
    name: "AsciiImage",
    group: "effects",
    kind: "Visual effect",
    reuse: "Reusable primitive",
    source: "src/components/AsciiImage.jsx",
    description: "Transforms a local image brightness map into a responsive ASCII canvas.",
    evidence: "Canvas rendering and resize behavior",
  },
  {
    id: "ascii-showcase-card",
    name: "AsciiShowcaseCard",
    group: "ui",
    kind: "Control",
    reuse: "Component candidate",
    source: "src/components/AsciiShowcaseCard.jsx",
    description: "Image card that reveals the original visual over generated ASCII on pointer hover or touch activation.",
    evidence: "Hover and touch reveal states",
  },
  {
    id: "split-button",
    name: "SplitButton",
    group: "ui",
    kind: "Control",
    reuse: "Reusable primitive",
    source: "src/components/SplitButton.jsx",
    description: "Segmented CTA with staggered per-letter odometer animation and status marker.",
    evidence: "Hover and focus animation",
  },
  {
    id: "odometer-word",
    name: "OdometerWord",
    group: "ui",
    kind: "Control",
    reuse: "Internal primitive",
    source: "src/components/SplitButton.jsx",
    description: "Accessible per-word glyph track used by SplitButton.",
    evidence: "CTA animation structure",
  },
  {
    id: "animated-text",
    name: "AnimatedText",
    group: "effects",
    kind: "Visual effect",
    reuse: "Reusable primitive",
    source: "src/recovered/text/AnimatedText.jsx",
    description: "Line-measured text entrance animation with reduced-motion support.",
    evidence: "Line reveal behavior",
  },
  {
    id: "glyph-field",
    name: "GlyphField",
    group: "effects",
    kind: "Visual effect",
    reuse: "Visual candidate",
    source: "src/recovered/glyph/GlyphField.jsx",
    description: "WebGL glyph field that reacts to cursor and scroll energy.",
    evidence: "Glyph animation and interaction",
  },
  {
    id: "glyph-field-backdrop",
    name: "GlyphFieldBackdrop",
    group: "effects",
    kind: "Visual effect",
    reuse: "Visual candidate",
    source: "src/recovered/glyph/GlyphFieldBackdrop.jsx",
    description: "Deferred, visibility-aware backdrop wrapper for GlyphField.",
    evidence: "Lazy backdrop behavior",
  },
  {
    id: "spiral-scene",
    name: "SpiralScene",
    group: "effects",
    kind: "Visual effect",
    reuse: "Visual candidate",
    source: "src/recovered/spiral/SpiralScene.jsx",
    description: "WebGL text spiral with hover, hold, charge, release, and reduced-motion states.",
    evidence: "Pointer-hold interaction states",
  },
  {
    id: "terminal",
    name: "Terminal",
    group: "ui",
    kind: "Control",
    reuse: "Component candidate",
    source: "src/recovered/terminal/Terminal.jsx",
    description: "Terminal display with sequential rows, cursor, and editable mode.",
    evidence: "Terminal row animation",
  },
  {
    id: "desktop-menu-card",
    name: "DesktopMenuCard",
    group: "ui",
    kind: "Navigation",
    reuse: "Component candidate",
    source: "src/recovered/menu/DesktopMenuCard.jsx",
    description: "Dither-framed desktop navigation and announcement marquee.",
    evidence: "Desktop menu structure",
  },
  {
    id: "mobile-menu-card",
    name: "MobileMenuCard",
    group: "ui",
    kind: "Navigation",
    reuse: "Component candidate",
    source: "src/recovered/menu/MobileMenuCard.jsx",
    description: "Mobile navigation card with menu expansion and announcement marquee.",
    evidence: "Mobile menu open state",
  },
  {
    id: "content-architecture-logo",
    name: "ContentArchitectureLogo",
    group: "ui",
    kind: "Brand",
    reuse: "Brand-specific",
    source: "src/recovered/menu/ContentArchitectureLogo.jsx",
    description: "Recovered brand logo component used by the navigation card.",
    evidence: "Brand asset rendering",
  },
];
