INSERT INTO color_palettes (id, name, mood, position) VALUES
  ('ember-editorial', 'Ember Editorial', 'Burnished warmth shaped for confident editorial moments', 19),
  ('persimmon-hour', 'Persimmon Hour', 'A warm sunset palette with polished studio restraint', 20),
  ('digital-amethyst', 'Digital Amethyst', 'Immersive violet balanced by a clear luminous surface', 21),
  ('velvet-signal', 'Velvet Signal', 'Expressive technology softened by cinematic material depth', 22),
  ('lagoon-modern', 'Lagoon Modern', 'Composed aquatic color for calm, capable interfaces', 23),
  ('mineral-current', 'Mineral Current', 'Quietly technical teal grounded in softened mineral tones', 24),
  ('linen-ritual', 'Linen Ritual', 'Material calm with a grounded, handcrafted point of view', 25),
  ('warm-archive', 'Warm Archive', 'Human warmth translated into timeless archival color', 26),
  ('night-moss', 'Night Moss', 'Botanical depth with a restorative contemporary finish', 27),
  ('blue-hour', 'Blue Hour', 'Measured evening blue with a quiet atmospheric lift', 28);

INSERT INTO color_palette_colors (palette_id, id, name, hex, foreground, role, position) VALUES
  ('ember-editorial', 'charred-serif', 'Charred Serif', '#211815', '#F4D8C7', 'lead', 1),
  ('ember-editorial', 'citrus-press', 'Citrus Press', '#D85B2A', '#1C0E09', 'accent', 2),
  ('ember-editorial', 'apricot-stock', 'Apricot Stock', '#F4D8C7', '#211815', 'companion', 3),
  ('persimmon-hour', 'afterglow-brown', 'Afterglow Brown', '#3A2020', '#F7E0CE', 'lead', 1),
  ('persimmon-hour', 'persimmon-mark', 'Persimmon Mark', '#D85B2A', '#1C0E09', 'accent', 2),
  ('persimmon-hour', 'peach-horizon', 'Peach Horizon', '#F7E0CE', '#3A2020', 'companion', 3),
  ('digital-amethyst', 'amethyst-night', 'Amethyst Night', '#181327', '#E8DDF1', 'lead', 1),
  ('digital-amethyst', 'orchid-pixel', 'Orchid Pixel', '#773389', '#F6ECFA', 'accent', 2),
  ('digital-amethyst', 'lavender-screen', 'Lavender Screen', '#E8DDF1', '#181327', 'companion', 3),
  ('velvet-signal', 'velvet-code', 'Velvet Code', '#2B1830', '#F1D6E9', 'lead', 1),
  ('velvet-signal', 'orchid-signal', 'Orchid Signal', '#773389', '#F8EEF8', 'accent', 2),
  ('velvet-signal', 'rose-interface', 'Rose Interface', '#F1D6E9', '#2B1830', 'companion', 3),
  ('lagoon-modern', 'lagoon-depth', 'Lagoon Depth', '#10292A', '#D7ECE8', 'lead', 1),
  ('lagoon-modern', 'tidal-marker', 'Tidal Marker', '#2C7A7B', '#FFFFFF', 'accent', 2),
  ('lagoon-modern', 'estuary-mist', 'Estuary Mist', '#D7ECE8', '#10292A', 'companion', 3),
  ('mineral-current', 'mineral-shadow', 'Mineral Shadow', '#1A302F', '#E1ECE7', 'lead', 1),
  ('mineral-current', 'current-glass', 'Current Glass', '#2C7A7B', '#FFFFFF', 'accent', 2),
  ('mineral-current', 'salted-jade', 'Salted Jade', '#E1ECE7', '#1A302F', 'companion', 3),
  ('linen-ritual', 'workshop-ink', 'Workshop Ink', '#2C2520', '#EED3BA', 'lead', 1),
  ('linen-ritual', 'woven-clay', 'Woven Clay', '#B78967', '#241711', 'accent', 2),
  ('linen-ritual', 'linen-hearth', 'Linen Hearth', '#EED3BA', '#2C2520', 'companion', 3),
  ('warm-archive', 'archive-umber', 'Archive Umber', '#35221D', '#EED3BA', 'lead', 1),
  ('warm-archive', 'patina-rose', 'Patina Rose', '#B8795F', '#26140F', 'accent', 2),
  ('warm-archive', 'hearth-paper', 'Hearth Paper', '#EED3BA', '#35221D', 'companion', 3),
  ('night-moss', 'forest-negative', 'Forest Negative', '#111D18', '#DDE9D8', 'lead', 1),
  ('night-moss', 'moss-index', 'Moss Index', '#3D7A57', '#FFFFFF', 'accent', 2),
  ('night-moss', 'lichen-paper', 'Lichen Paper', '#DDE9D8', '#111D18', 'companion', 3),
  ('blue-hour', 'twilight-ink', 'Twilight Ink', '#111C38', '#DCE8F4', 'lead', 1),
  ('blue-hour', 'evening-index', 'Evening Index', '#446FA6', '#FFFFFF', 'accent', 2),
  ('blue-hour', 'clouded-blue', 'Clouded Blue', '#DCE8F4', '#111C38', 'companion', 3);

INSERT INTO color_collection_palettes (collection_id, palette_id, position) VALUES
  ('color-of-the-year-2025', 'ember-editorial', 4),
  ('color-of-the-year-2025', 'persimmon-hour', 5),
  ('color-of-the-year-2024', 'digital-amethyst', 4),
  ('color-of-the-year-2024', 'velvet-signal', 5),
  ('color-of-the-year-2023', 'lagoon-modern', 4),
  ('color-of-the-year-2023', 'mineral-current', 5),
  ('color-of-the-year-2022', 'linen-ritual', 4),
  ('color-of-the-year-2022', 'warm-archive', 5);
