ALTER TABLE color_collections
  ADD COLUMN featured_colors JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE color_collections
  ADD CONSTRAINT color_collections_featured_colors_array_check
  CHECK (jsonb_typeof(featured_colors) = 'array' AND jsonb_array_length(featured_colors) > 0);

INSERT INTO color_palettes (id, name, mood, position) VALUES
  ('cloud-canvas', 'Cloud Canvas', 'Airy restraint grounded by a graphite edge', 29),
  ('quiet-spectrum', 'Quiet Spectrum', 'Soft violet nuance framed by contemplative white', 30),
  ('coastal-cloud', 'Coastal Cloud', 'A serene white lifted by cool aqueous depth', 31),
  ('mocha-atelier', 'Mocha Atelier', 'Sensorial brown with a refined cream finish', 32),
  ('mocha-botanical', 'Mocha Botanical', 'Earthy indulgence balanced by restorative green', 33),
  ('mocha-blue', 'Mocha Blue', 'Comforting brown contrasted with composed evening blue', 34),
  ('peach-nocturne', 'Peach Nocturne', 'Gentle peach made cinematic with cocoa shadow', 35),
  ('peach-tide', 'Peach Tide', 'Warm softness paired with cool coastal clarity', 36),
  ('peach-plum', 'Peach Plum', 'Nurturing peach with expressive editorial depth', 37),
  ('viva-noir', 'Viva Noir', 'Fearless crimson sharpened by nocturnal contrast', 38),
  ('viva-cobalt', 'Viva Cobalt', 'Energetic magenta anchored by confident blue', 39),
  ('viva-garden', 'Viva Garden', 'A natural red statement softened by botanical calm', 40),
  ('peri-night', 'Peri Night', 'Inventive periwinkle illuminated against deep indigo', 41),
  ('peri-clay', 'Peri Clay', 'Future-facing periwinkle grounded by tactile neutrals', 42),
  ('peri-mint', 'Peri Mint', 'Playful blue-violet balanced by restorative green', 43),
  ('sunlit-concrete', 'Sunlit Concrete', 'Optimistic yellow supported by enduring gray', 44),
  ('solar-structure', 'Solar Structure', 'Bright resolve expressed through cool architecture', 45),
  ('gray-daybreak', 'Gray Daybreak', 'Dependable gray awakened by a clear solar accent', 46),
  ('classic-blue-night', 'Classic Blue Night', 'Enduring blue with calm nocturnal confidence', 47),
  ('classic-blue-brass', 'Classic Blue Brass', 'Foundational blue refined with a warm metallic note', 48),
  ('classic-blue-coral', 'Classic Blue Coral', 'Stable blue enlivened by a human coral gesture', 49),
  ('coral-night', 'Coral Night', 'Sociable coral glowing against a dramatic dark field', 50),
  ('coral-navy', 'Coral Navy', 'Vibrant warmth balanced by poised maritime blue', 51),
  ('coral-garden', 'Coral Garden', 'Life-affirming coral rooted in botanical depth', 52);

INSERT INTO color_palette_colors (palette_id, id, name, hex, foreground, role, position) VALUES
  ('cloud-canvas', 'graphite-veil', 'Graphite Veil', '#262729', '#F0EEE9', 'lead', 1),
  ('cloud-canvas', 'silver-air', 'Silver Air', '#A9AFB4', '#171819', 'accent', 2),
  ('cloud-canvas', 'cloud-dancer-canvas', 'Cloud Dancer', '#F0EEE9', '#262729', 'companion', 3),
  ('quiet-spectrum', 'night-plum', 'Night Plum', '#2D2933', '#F0EEE9', 'lead', 1),
  ('quiet-spectrum', 'mist-lavender', 'Mist Lavender', '#C9C3D2', '#241F2A', 'accent', 2),
  ('quiet-spectrum', 'cloud-dancer-spectrum', 'Cloud Dancer', '#F0EEE9', '#2D2933', 'companion', 3),
  ('coastal-cloud', 'deep-fjord', 'Deep Fjord', '#173033', '#F0EEE9', 'lead', 1),
  ('coastal-cloud', 'sea-glass', 'Sea Glass', '#8FB3AF', '#142321', 'accent', 2),
  ('coastal-cloud', 'cloud-dancer-coast', 'Cloud Dancer', '#F0EEE9', '#173033', 'companion', 3),
  ('mocha-atelier', 'cacao-ink', 'Cacao Ink', '#2A1B17', '#EFE2D8', 'lead', 1),
  ('mocha-atelier', 'mocha-mousse-atelier', 'Mocha Mousse', '#A47864', '#211511', 'accent', 2),
  ('mocha-atelier', 'cream-pour', 'Cream Pour', '#EFE2D8', '#2A1B17', 'companion', 3),
  ('mocha-botanical', 'pine-roast', 'Pine Roast', '#203127', '#DDE3D4', 'lead', 1),
  ('mocha-botanical', 'mocha-mousse-botanical', 'Mocha Mousse', '#A47864', '#211511', 'accent', 2),
  ('mocha-botanical', 'sage-foam', 'Sage Foam', '#DDE3D4', '#203127', 'companion', 3),
  ('mocha-blue', 'indigo-roast', 'Indigo Roast', '#1E2638', '#DDE5EF', 'lead', 1),
  ('mocha-blue', 'mocha-mousse-blue', 'Mocha Mousse', '#A47864', '#211511', 'accent', 2),
  ('mocha-blue', 'powder-blue', 'Powder Blue', '#DDE5EF', '#1E2638', 'companion', 3),
  ('peach-nocturne', 'cocoa-noir', 'Cocoa Noir', '#2E1C19', '#FFF0E7', 'lead', 1),
  ('peach-nocturne', 'peach-fuzz-nocturne', 'Peach Fuzz', '#FFBE98', '#291812', 'accent', 2),
  ('peach-nocturne', 'peach-paper', 'Peach Paper', '#FFF0E7', '#2E1C19', 'companion', 3),
  ('peach-tide', 'deep-teal', 'Deep Teal', '#173334', '#DCEAE7', 'lead', 1),
  ('peach-tide', 'peach-fuzz-tide', 'Peach Fuzz', '#FFBE98', '#291812', 'accent', 2),
  ('peach-tide', 'sea-salt', 'Sea Salt', '#DCEAE7', '#173334', 'companion', 3),
  ('peach-plum', 'mulberry-ink', 'Mulberry Ink', '#3B2236', '#F2DEE5', 'lead', 1),
  ('peach-plum', 'peach-fuzz-plum', 'Peach Fuzz', '#FFBE98', '#291812', 'accent', 2),
  ('peach-plum', 'rose-mist', 'Rose Mist', '#F2DEE5', '#3B2236', 'companion', 3),
  ('viva-noir', 'noir-petal', 'Noir Petal', '#24151A', '#F8E3E8', 'lead', 1),
  ('viva-noir', 'viva-magenta-noir', 'Viva Magenta', '#BB2649', '#FFFFFF', 'accent', 2),
  ('viva-noir', 'petal-white', 'Petal White', '#F8E3E8', '#24151A', 'companion', 3),
  ('viva-cobalt', 'cobalt-depth', 'Cobalt Depth', '#14284A', '#DFE6F1', 'lead', 1),
  ('viva-cobalt', 'viva-magenta-cobalt', 'Viva Magenta', '#BB2649', '#FFFFFF', 'accent', 2),
  ('viva-cobalt', 'blue-paper', 'Blue Paper', '#DFE6F1', '#14284A', 'companion', 3),
  ('viva-garden', 'garden-shadow', 'Garden Shadow', '#1F352C', '#E0E7DC', 'lead', 1),
  ('viva-garden', 'viva-magenta-garden', 'Viva Magenta', '#BB2649', '#FFFFFF', 'accent', 2),
  ('viva-garden', 'sage-paper', 'Sage Paper', '#E0E7DC', '#1F352C', 'companion', 3),
  ('peri-night', 'indigo-night', 'Indigo Night', '#191A31', '#E4E3F3', 'lead', 1),
  ('peri-night', 'very-peri-night', 'Very Peri', '#6667AB', '#FFFFFF', 'accent', 2),
  ('peri-night', 'peri-mist', 'Peri Mist', '#E4E3F3', '#191A31', 'companion', 3),
  ('peri-clay', 'clay-shadow', 'Clay Shadow', '#3A2925', '#E9DDD3', 'lead', 1),
  ('peri-clay', 'very-peri-clay', 'Very Peri', '#6667AB', '#FFFFFF', 'accent', 2),
  ('peri-clay', 'sand-veil', 'Sand Veil', '#E9DDD3', '#3A2925', 'companion', 3),
  ('peri-mint', 'mint-shadow', 'Mint Shadow', '#20352F', '#DCE8E2', 'lead', 1),
  ('peri-mint', 'very-peri-mint', 'Very Peri', '#6667AB', '#FFFFFF', 'accent', 2),
  ('peri-mint', 'mint-fog', 'Mint Fog', '#DCE8E2', '#20352F', 'companion', 3),
  ('sunlit-concrete', 'concrete-depth', 'Concrete Depth', '#303235', '#F5DF4D', 'lead', 1),
  ('sunlit-concrete', 'illuminating-sun', 'Illuminating', '#F5DF4D', '#24230E', 'accent', 2),
  ('sunlit-concrete', 'ultimate-gray-sun', 'Ultimate Gray', '#97999B', '#1B1C1D', 'companion', 3),
  ('solar-structure', 'structural-blue', 'Structural Blue', '#25333A', '#F5DF4D', 'lead', 1),
  ('solar-structure', 'illuminating-structure', 'Illuminating', '#F5DF4D', '#24230E', 'accent', 2),
  ('solar-structure', 'ultimate-gray-structure', 'Ultimate Gray', '#97999B', '#1B1C1D', 'companion', 3),
  ('gray-daybreak', 'ultimate-gray-daybreak', 'Ultimate Gray', '#97999B', '#1B1C1D', 'lead', 1),
  ('gray-daybreak', 'illuminating-daybreak', 'Illuminating', '#F5DF4D', '#24230E', 'accent', 2),
  ('gray-daybreak', 'daybreak-paper', 'Daybreak Paper', '#F5F3E8', '#303235', 'companion', 3),
  ('classic-blue-night', 'midnight-foundation', 'Midnight Foundation', '#101A28', '#DCE8F1', 'lead', 1),
  ('classic-blue-night', 'classic-blue-night-color', 'Classic Blue', '#0F4C81', '#FFFFFF', 'accent', 2),
  ('classic-blue-night', 'sky-paper', 'Sky Paper', '#DCE8F1', '#101A28', 'companion', 3),
  ('classic-blue-brass', 'classic-blue-brass-color', 'Classic Blue', '#0F4C81', '#FFFFFF', 'lead', 1),
  ('classic-blue-brass', 'quiet-brass', 'Quiet Brass', '#C3A457', '#241E0E', 'accent', 2),
  ('classic-blue-brass', 'heritage-linen', 'Heritage Linen', '#F1E8D8', '#182235', 'companion', 3),
  ('classic-blue-coral', 'classic-blue-coral-color', 'Classic Blue', '#0F4C81', '#FFFFFF', 'lead', 1),
  ('classic-blue-coral', 'coral-gesture', 'Coral Gesture', '#E37C70', '#2B1512', 'accent', 2),
  ('classic-blue-coral', 'blush-paper', 'Blush Paper', '#F2DFDC', '#273142', 'companion', 3),
  ('coral-night', 'coral-nocturne', 'Coral Nocturne', '#2B1C21', '#FCE3DD', 'lead', 1),
  ('coral-night', 'living-coral-night', 'Living Coral', '#FF6F61', '#2B1210', 'accent', 2),
  ('coral-night', 'shell-paper', 'Shell Paper', '#FCE3DD', '#2B1C21', 'companion', 3),
  ('coral-navy', 'maritime-ink', 'Maritime Ink', '#14233B', '#E5E9ED', 'lead', 1),
  ('coral-navy', 'living-coral-navy', 'Living Coral', '#FF6F61', '#2B1210', 'accent', 2),
  ('coral-navy', 'silver-foam', 'Silver Foam', '#E5E9ED', '#14233B', 'companion', 3),
  ('coral-garden', 'herbal-shadow', 'Herbal Shadow', '#20352B', '#E2E8DA', 'lead', 1),
  ('coral-garden', 'living-coral-garden', 'Living Coral', '#FF6F61', '#2B1210', 'accent', 2),
  ('coral-garden', 'herbal-paper', 'Herbal Paper', '#E2E8DA', '#20352B', 'companion', 3);

INSERT INTO color_collections (
  id, name, description, year, featured_color_name, featured_hex, position, featured_colors
) VALUES
  ('color-of-the-year-2026', '2026 — Cloud Dancer', 'A lofty off-white associated with calm, reflection, and a renewed creative canvas.', 2026, 'Cloud Dancer', '#F0EEE9', 1, '[{"name":"Cloud Dancer","code":"11-4201","hex":"#F0EEE9"}]'::jsonb),
  ('color-of-the-year-2025', '2025 — Mocha Mousse', 'A warming brown shaped by comfort, thoughtful indulgence, and everyday richness.', 2025, 'Mocha Mousse', '#A47864', 2, '[{"name":"Mocha Mousse","code":"17-1230","hex":"#A47864"}]'::jsonb),
  ('color-of-the-year-2024', '2024 — Peach Fuzz', 'A gentle peach expressing warmth, care, connection, and tactile softness.', 2024, 'Peach Fuzz', '#FFBE98', 3, '[{"name":"Peach Fuzz","code":"13-1023","hex":"#FFBE98"}]'::jsonb),
  ('color-of-the-year-2023', '2023 — Viva Magenta', 'A courageous crimson red expressing energy, optimism, and fearless self-expression.', 2023, 'Viva Magenta', '#BB2649', 4, '[{"name":"Viva Magenta","code":"18-1750","hex":"#BB2649"}]'::jsonb),
  ('color-of-the-year-2022', '2022 — Very Peri', 'A dynamic periwinkle blue encouraging invention, curiosity, and creative confidence.', 2022, 'Very Peri', '#6667AB', 5, '[{"name":"Very Peri","code":"17-3938","hex":"#6667AB"}]'::jsonb),
  ('color-of-the-year-2021', '2021 — Illuminating + Ultimate Gray', 'A pairing of bright optimism and dependable resilience, designed to support one another.', 2021, 'Illuminating', '#F5DF4D', 6, '[{"name":"Illuminating","code":"13-0647","hex":"#F5DF4D"},{"name":"Ultimate Gray","code":"17-5104","hex":"#97999B"}]'::jsonb),
  ('color-of-the-year-2020', '2020 — Classic Blue', 'A timeless deep blue offering calm, confidence, connection, and a stable foundation.', 2020, 'Classic Blue', '#0F4C81', 7, '[{"name":"Classic Blue","code":"19-4052","hex":"#0F4C81"}]'::jsonb),
  ('color-of-the-year-2019', '2019 — Living Coral', 'A vibrant coral expressing sociability, warmth, optimism, and life-affirming energy.', 2019, 'Living Coral', '#FF6F61', 8, '[{"name":"Living Coral","code":"16-1546","hex":"#FF6F61"}]'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  year = EXCLUDED.year,
  featured_color_name = EXCLUDED.featured_color_name,
  featured_hex = EXCLUDED.featured_hex,
  position = EXCLUDED.position,
  featured_colors = EXCLUDED.featured_colors,
  is_published = TRUE,
  updated_at = now();

DELETE FROM color_collection_palettes
WHERE collection_id IN ('color-of-the-year-2026', 'color-of-the-year-2025', 'color-of-the-year-2024', 'color-of-the-year-2023', 'color-of-the-year-2022', 'color-of-the-year-2021', 'color-of-the-year-2020', 'color-of-the-year-2019');

INSERT INTO color_collection_palettes (collection_id, palette_id, position) VALUES
  ('color-of-the-year-2026', 'cloud-canvas', 1),
  ('color-of-the-year-2026', 'quiet-spectrum', 2),
  ('color-of-the-year-2026', 'coastal-cloud', 3),
  ('color-of-the-year-2025', 'mocha-atelier', 1),
  ('color-of-the-year-2025', 'mocha-botanical', 2),
  ('color-of-the-year-2025', 'mocha-blue', 3),
  ('color-of-the-year-2024', 'peach-nocturne', 1),
  ('color-of-the-year-2024', 'peach-tide', 2),
  ('color-of-the-year-2024', 'peach-plum', 3),
  ('color-of-the-year-2023', 'viva-noir', 1),
  ('color-of-the-year-2023', 'viva-cobalt', 2),
  ('color-of-the-year-2023', 'viva-garden', 3),
  ('color-of-the-year-2022', 'peri-night', 1),
  ('color-of-the-year-2022', 'peri-clay', 2),
  ('color-of-the-year-2022', 'peri-mint', 3),
  ('color-of-the-year-2021', 'sunlit-concrete', 1),
  ('color-of-the-year-2021', 'solar-structure', 2),
  ('color-of-the-year-2021', 'gray-daybreak', 3),
  ('color-of-the-year-2020', 'classic-blue-night', 1),
  ('color-of-the-year-2020', 'classic-blue-brass', 2),
  ('color-of-the-year-2020', 'classic-blue-coral', 3),
  ('color-of-the-year-2019', 'coral-night', 1),
  ('color-of-the-year-2019', 'coral-navy', 2),
  ('color-of-the-year-2019', 'coral-garden', 3);
