CREATE TABLE flow_categories (
  id BIGSERIAL PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name TEXT NOT NULL UNIQUE CHECK (btrim(name) <> ''),
  position INTEGER NOT NULL UNIQUE CHECK (position > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE flow_types (
  id BIGSERIAL PRIMARY KEY,
  category_id BIGINT NOT NULL REFERENCES flow_categories(id) ON DELETE RESTRICT,
  slug TEXT NOT NULL CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name TEXT NOT NULL CHECK (btrim(name) <> ''),
  position INTEGER NOT NULL CHECK (position > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (category_id, slug),
  UNIQUE (category_id, position)
);

CREATE TABLE flow_classifications (
  flow_id BIGINT PRIMARY KEY REFERENCES flows(id) ON DELETE CASCADE,
  flow_type_id BIGINT NOT NULL REFERENCES flow_types(id) ON DELETE RESTRICT,
  status TEXT NOT NULL CHECK (status IN ('needs_review', 'approved')),
  confidence NUMERIC(3, 2) CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
  source TEXT NOT NULL CHECK (source IN ('manual', 'rule')),
  reviewed_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((status = 'approved') = (reviewed_at IS NOT NULL))
);

CREATE INDEX flow_types_category_position_idx
  ON flow_types(category_id, position);
CREATE INDEX flow_classifications_review_queue_idx
  ON flow_classifications(status, updated_at DESC, flow_id);
CREATE INDEX flow_classifications_type_idx
  ON flow_classifications(flow_type_id, flow_id)
  WHERE status = 'approved';

INSERT INTO flow_categories (slug, name, position) VALUES
  ('authentication', 'Authentication', 1),
  ('onboarding', 'Onboarding', 2),
  ('discovery-navigation', 'Discovery & Navigation', 3),
  ('search', 'Search', 4),
  ('content-detail', 'Content & Detail', 5),
  ('creation-editing', 'Creation & Editing', 6),
  ('communication-collaboration', 'Communication & Collaboration', 7),
  ('commerce-checkout', 'Commerce & Checkout', 8),
  ('monetization', 'Monetization', 9),
  ('billing', 'Billing', 10),
  ('account-settings', 'Account & Settings', 11),
  ('retention-engagement', 'Retention & Engagement', 12),
  ('system-privacy-support', 'System, Privacy & Support', 13);

INSERT INTO flow_types (category_id, slug, name, position)
SELECT category.id, type.slug, type.name, type.position
FROM (
  VALUES
    ('authentication', 'sign-in', 'Sign in', 1),
    ('authentication', 'sign-up', 'Sign up', 2),
    ('authentication', 'social-sign-in', 'Social sign-in', 3),
    ('authentication', 'single-sign-on', 'SSO', 4),
    ('authentication', 'password-reset', 'Password reset', 5),
    ('authentication', 'email-phone-verification', 'Email / phone verification', 6),
    ('authentication', 'mfa-passkeys', 'MFA / passkeys', 7),
    ('authentication', 'identity-verification', 'Identity verification', 8),
    ('onboarding', 'welcome', 'Welcome / value proposition', 1),
    ('onboarding', 'goal-selection', 'Choose goals or intent', 2),
    ('onboarding', 'personalization', 'Personalization questions', 3),
    ('onboarding', 'profile-setup', 'Profile setup', 4),
    ('onboarding', 'guided-tutorial', 'Guided tutorial', 5),
    ('onboarding', 'data-import', 'Import / connect data', 6),
    ('onboarding', 'team-invite', 'Invite team members', 7),
    ('onboarding', 'first-success', 'First successful action', 8),
    ('onboarding', 'onboarding-checklist', 'Onboarding checklist', 9),
    ('discovery-navigation', 'home-dashboard', 'Home / dashboard', 1),
    ('discovery-navigation', 'explore-browse', 'Explore / browse', 2),
    ('discovery-navigation', 'categories', 'Categories', 3),
    ('discovery-navigation', 'feed', 'Feed', 4),
    ('discovery-navigation', 'navigation-menu', 'Navigation menu', 5),
    ('discovery-navigation', 'tab-bar-sidebar', 'Tab bar / sidebar', 6),
    ('discovery-navigation', 'recently-viewed', 'Recently viewed / continue', 7),
    ('search', 'search-entry', 'Search entry', 1),
    ('search', 'recent-searches', 'Recent searches', 2),
    ('search', 'suggestions', 'Search suggestions', 3),
    ('search', 'autocomplete', 'Autocomplete', 4),
    ('search', 'results', 'Search results', 5),
    ('search', 'filters-sorting', 'Filters & sorting', 6),
    ('search', 'no-results', 'No results', 7),
    ('search', 'voice-visual-search', 'Voice / visual search', 8),
    ('content-detail', 'article-post-detail', 'Article / post detail', 1),
    ('content-detail', 'product-listing-detail', 'Product / listing detail', 2),
    ('content-detail', 'task-project-detail', 'Task / project detail', 3),
    ('content-detail', 'media-detail-player', 'Media detail / player', 4),
    ('content-detail', 'profile-detail', 'Profile detail', 5),
    ('content-detail', 'order-booking-detail', 'Order / booking detail', 6),
    ('content-detail', 'reviews-ratings', 'Reviews and ratings', 7),
    ('creation-editing', 'create-item', 'Create new item', 1),
    ('creation-editing', 'edit-item', 'Edit item', 2),
    ('creation-editing', 'draft-autosave', 'Draft and autosave', 3),
    ('creation-editing', 'upload-media-file', 'Upload media / file', 4),
    ('creation-editing', 'add-assignee', 'Add collaborator or assignee', 5),
    ('creation-editing', 'duplicate-template', 'Duplicate / template', 6),
    ('creation-editing', 'publish-submit', 'Publish / submit', 7),
    ('creation-editing', 'delete-archive', 'Delete / archive', 8),
    ('communication-collaboration', 'start-conversation', 'Start conversation', 1),
    ('communication-collaboration', 'send-message', 'Send message', 2),
    ('communication-collaboration', 'inbox-conversation', 'Inbox / conversation detail', 3),
    ('communication-collaboration', 'comment-reply', 'Comment / reply', 4),
    ('communication-collaboration', 'mention-notify', 'Mention / notify teammate', 5),
    ('communication-collaboration', 'share-item', 'Share item', 6),
    ('communication-collaboration', 'invite-member', 'Invite member', 7),
    ('communication-collaboration', 'manage-members-roles', 'Manage members / roles', 8),
    ('communication-collaboration', 'activity-updates', 'Activity and updates', 9),
    ('commerce-checkout', 'browse-products-services', 'Browse products or services', 1),
    ('commerce-checkout', 'product-listing-selection', 'Product / listing selection', 2),
    ('commerce-checkout', 'cart', 'Cart', 3),
    ('commerce-checkout', 'checkout', 'Checkout', 4),
    ('commerce-checkout', 'address-delivery', 'Address / delivery details', 5),
    ('commerce-checkout', 'booking-reservation', 'Booking or reservation', 6),
    ('commerce-checkout', 'order-confirmation', 'Order confirmation', 7),
    ('commerce-checkout', 'order-tracking', 'Order tracking', 8),
    ('commerce-checkout', 'returns-exchanges', 'Returns or exchanges', 9),
    ('monetization', 'pricing-overview', 'Pricing overview', 1),
    ('monetization', 'paywall', 'Paywall', 2),
    ('monetization', 'plan-selection', 'Plan selection', 3),
    ('monetization', 'free-trial', 'Free trial', 4),
    ('monetization', 'upgrade-prompt', 'Upgrade prompt', 5),
    ('monetization', 'usage-limit-upsell', 'Usage-limit upsell', 6),
    ('monetization', 'discount-offer', 'Discount offer', 7),
    ('billing', 'manage-subscription', 'Manage subscription', 1),
    ('billing', 'change-plan', 'Change plan', 2),
    ('billing', 'payment-method', 'Change payment method', 3),
    ('billing', 'invoices', 'View invoices', 4),
    ('billing', 'cancel-subscription', 'Cancel subscription', 5),
    ('billing', 'refund', 'Request refund', 6),
    ('billing', 'restore-purchase', 'Restore purchase', 7),
    ('account-settings', 'view-account', 'View account', 1),
    ('account-settings', 'edit-profile', 'Edit profile', 2),
    ('account-settings', 'preferences', 'Preferences', 3),
    ('account-settings', 'security-settings', 'Security settings', 4),
    ('account-settings', 'workspace-settings', 'Workspace / organization settings', 5),
    ('account-settings', 'integrations', 'Connected integrations', 6),
    ('account-settings', 'appearance-language', 'Appearance / language', 7),
    ('account-settings', 'data-export', 'Data export', 8),
    ('account-settings', 'deactivate-delete-account', 'Deactivate or delete account', 9),
    ('retention-engagement', 'notification-center', 'Notification center', 1),
    ('retention-engagement', 'notification-prompt', 'Notification prompt', 2),
    ('retention-engagement', 'daily-check-in', 'Daily check-in', 3),
    ('retention-engagement', 'streak-milestone', 'Streaks and milestones', 4),
    ('retention-engagement', 'rewards-achievements', 'Rewards / achievements', 5),
    ('retention-engagement', 'reminders', 'Reminders', 6),
    ('retention-engagement', 're-engagement', 'Re-engagement prompt', 7),
    ('retention-engagement', 'feedback-request', 'Feedback request', 8),
    ('retention-engagement', 'referral-reward', 'Referral / invite reward', 9),
    ('system-privacy-support', 'device-permissions', 'Device permissions', 1),
    ('system-privacy-support', 'privacy-consent', 'Privacy consent', 2),
    ('system-privacy-support', 'legal-acknowledgement', 'Terms / legal acknowledgement', 3),
    ('system-privacy-support', 'system-settings-handoff', 'System settings handoff', 4),
    ('system-privacy-support', 'help-center', 'Help center', 5),
    ('system-privacy-support', 'contact-support', 'Contact support', 6),
    ('system-privacy-support', 'error-recovery', 'Error state and recovery', 7),
    ('system-privacy-support', 'empty-state', 'Empty state', 8),
    ('system-privacy-support', 'offline-maintenance', 'Offline / maintenance state', 9)
) AS type(category_slug, slug, name, position)
JOIN flow_categories category ON category.slug = type.category_slug;
