-- Recreates every CHECK constraint dropped by migration 0083, verbatim.
--
-- Not a migration: run it by hand if you want the database-level rules back.
--   psql "$DATABASE_URL" -f scripts/restore-check-constraints.sql
--
-- Each statement will fail if rows written since 0083 violate the rule it restores.
-- That failure is the useful part: it tells you exactly which invariant broke while the
-- constraint was absent. Fix the data, then re-run.

ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_effort_check CHECK ((effort = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'xhigh'::text, 'max'::text])));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_platform_check CHECK ((platform = ANY (ARRAY['ios'::text, 'android'::text, 'web'::text])));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_prompt_version_check CHECK ((prompt_version > 0));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_provider_model_check CHECK (((length(provider_model) >= 1) AND (length(provider_model) <= 160)));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_research_context_sha256_check CHECK ((research_context_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_result_check CHECK (((jsonb_typeof(result) = 'object'::text) AND (result ?& ARRAY['flowId'::text, 'modelAssessment'::text, 'claimReconciliation'::text, 'implementationKnowledge'::text, 'risks'::text, 'qualityChecks'::text])));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_result_sha256_check CHECK ((result_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_review_recommendation_check CHECK (((jsonb_typeof(review_recommendation) = 'object'::text) AND (review_recommendation ?& ARRAY['solReview'::text, 'reasons'::text])));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_review_status_check CHECK ((review_status = ANY (ARRAY['needs_review'::text, 'approved'::text, 'rejected'::text, 'superseded'::text])));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_revision_number_check CHECK ((revision_number > 0));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_source_fingerprint_check CHECK ((source_fingerprint ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_source_flow_id_check CHECK ((btrim(source_flow_id) <> ''::text));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_usage_check CHECK ((jsonb_typeof(usage) = 'object'::text));
ALTER TABLE app_flow_reconciliations ADD CONSTRAINT app_flow_reconciliations_visual_analysis_sha256_check CHECK ((visual_analysis_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_flow_versions ADD CONSTRAINT app_flow_versions_position_check CHECK (("position" > 0));
ALTER TABLE app_flow_versions ADD CONSTRAINT app_flow_versions_source_flow_id_check CHECK ((btrim(source_flow_id) <> ''::text));
ALTER TABLE app_flow_versions ADD CONSTRAINT app_flow_versions_steps_check CHECK ((jsonb_typeof(steps) = 'array'::text));
ALTER TABLE app_flow_versions ADD CONSTRAINT app_flow_versions_tags_check CHECK ((jsonb_typeof(tags) = 'array'::text));
ALTER TABLE app_flow_versions ADD CONSTRAINT app_flow_versions_title_check CHECK ((btrim(title) <> ''::text));
ALTER TABLE app_flows ADD CONSTRAINT app_flows_position_check CHECK (("position" > 0));
ALTER TABLE app_flows ADD CONSTRAINT app_flows_source_flow_id_check CHECK ((btrim(source_flow_id) <> ''::text));
ALTER TABLE app_flows ADD CONSTRAINT app_flows_steps_check CHECK ((jsonb_typeof(steps) = 'array'::text));
ALTER TABLE app_flows ADD CONSTRAINT app_flows_tags_check CHECK ((jsonb_typeof(tags) = 'array'::text));
ALTER TABLE app_flows ADD CONSTRAINT app_flows_title_check CHECK ((btrim(title) <> ''::text));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_check CHECK (((region_x + region_width) <= (1)::double precision));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_check1 CHECK (((region_y + region_height) <= (1)::double precision));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_component_family_check CHECK (((length(component_family) >= 1) AND (length(component_family) <= 160)));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_component_variant_check CHECK (((length(component_variant) >= 1) AND (length(component_variant) <= 160)));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_crop_sha256_check CHECK ((crop_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_prompt_version_check CHECK ((prompt_version > 0));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_provider_model_check CHECK (((length(provider_model) >= 1) AND (length(provider_model) <= 160)));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_region_height_check CHECK (((region_height > (0)::double precision) AND (region_height <= (1)::double precision)));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_region_width_check CHECK (((region_width > (0)::double precision) AND (region_width <= (1)::double precision)));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_region_x_check CHECK (((region_x >= (0)::double precision) AND (region_x <= (1)::double precision)));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_region_y_check CHECK (((region_y >= (0)::double precision) AND (region_y <= (1)::double precision)));
ALTER TABLE app_knowledge_component_crops ADD CONSTRAINT app_knowledge_component_crops_source_sha256_check CHECK ((source_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_knowledge_design_system_chunks ADD CONSTRAINT app_knowledge_design_system_chunks_attempt_count_check CHECK ((attempt_count >= 0));
ALTER TABLE app_knowledge_design_system_chunks ADD CONSTRAINT app_knowledge_design_system_chunks_chunk_key_check CHECK ((chunk_key ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_knowledge_design_system_chunks ADD CONSTRAINT app_knowledge_design_system_chunks_fragment_check CHECK (((fragment IS NULL) OR (jsonb_typeof(fragment) = 'object'::text)));
ALTER TABLE app_knowledge_design_system_chunks ADD CONSTRAINT app_knowledge_design_system_chunks_ordinal_check CHECK ((ordinal >= 0));
ALTER TABLE app_knowledge_design_system_chunks ADD CONSTRAINT app_knowledge_design_system_chunks_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'complete'::text, 'failed'::text])));
ALTER TABLE app_knowledge_evidence_cache ADD CONSTRAINT app_knowledge_evidence_cache_analysis_check CHECK ((jsonb_typeof(analysis) = 'object'::text));
ALTER TABLE app_knowledge_evidence_cache ADD CONSTRAINT app_knowledge_evidence_cache_cache_key_check CHECK ((cache_key ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_knowledge_evidence_cache ADD CONSTRAINT app_knowledge_evidence_cache_normalized_visual_sha256_check CHECK ((normalized_visual_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_knowledge_evidence_cache ADD CONSTRAINT app_knowledge_evidence_cache_platform_check CHECK ((platform = ANY (ARRAY['ios'::text, 'android'::text, 'web'::text])));
ALTER TABLE app_knowledge_evidence_cache ADD CONSTRAINT app_knowledge_evidence_cache_prompt_version_check CHECK ((prompt_version > 0));
ALTER TABLE app_knowledge_evidence_cache ADD CONSTRAINT app_knowledge_evidence_cache_provider_model_check CHECK (((length(provider_model) >= 1) AND (length(provider_model) <= 160)));
ALTER TABLE app_knowledge_evidence_overrides ADD CONSTRAINT app_knowledge_evidence_overrides_decision_check CHECK ((decision = ANY (ARRAY['eligible'::text, 'quarantined'::text])));
ALTER TABLE app_knowledge_evidence_overrides ADD CONSTRAINT app_knowledge_evidence_overrides_reason_check CHECK (((length(reason) >= 1) AND (length(reason) <= 1000)));
ALTER TABLE app_knowledge_job_evidence ADD CONSTRAINT app_knowledge_job_evidence_analysis_check CHECK (((analysis IS NULL) OR (jsonb_typeof(analysis) = 'object'::text)));
ALTER TABLE app_knowledge_job_evidence ADD CONSTRAINT app_knowledge_job_evidence_attempt_count_check CHECK ((attempt_count >= 0));
ALTER TABLE app_knowledge_job_evidence ADD CONSTRAINT app_knowledge_job_evidence_cache_key_check CHECK (((cache_key IS NULL) OR (cache_key ~ '^[0-9a-f]{64}$'::text)));
ALTER TABLE app_knowledge_job_evidence ADD CONSTRAINT app_knowledge_job_evidence_evidence_id_check CHECK (((length(evidence_id) >= 1) AND (length(evidence_id) <= 300)));
ALTER TABLE app_knowledge_job_evidence ADD CONSTRAINT app_knowledge_job_evidence_kind_check CHECK ((kind = ANY (ARRAY['screen'::text, 'flow_step'::text, 'ui_element'::text])));
ALTER TABLE app_knowledge_job_evidence ADD CONSTRAINT app_knowledge_job_evidence_ordinal_check CHECK ((ordinal >= 0));
ALTER TABLE app_knowledge_job_evidence ADD CONSTRAINT app_knowledge_job_evidence_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'complete'::text, 'failed'::text, 'cached'::text, 'quarantined'::text, 'duplicate'::text])));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_cache_hit_count_check CHECK ((cache_hit_count >= 0));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_check CHECK ((done_count <= total_count));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_design_system_seed_outcome_check CHECK ((design_system_seed_outcome = ANY (ARRAY['seeded'::text, 'replaced'::text, 'unchanged'::text, 'conflict'::text])));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_done_count_check CHECK ((done_count >= 0));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_evidence_manifest_check CHECK (((evidence_manifest IS NULL) OR (jsonb_typeof(evidence_manifest) = 'array'::text)));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_failed_count_check CHECK ((failed_count >= 0));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_prompt_version_check CHECK ((prompt_version > 0));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_provider_model_check CHECK (((length(provider_model) >= 1) AND (length(provider_model) <= 160)));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_request_origin_check CHECK ((request_origin = ANY (ARRAY['manual'::text, 'retry'::text, 'regeneration'::text, 'automatic'::text])));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_source_sha256_check CHECK (((source_sha256 IS NULL) OR (source_sha256 ~ '^[0-9a-f]{64}$'::text)));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_stage_check CHECK ((stage = ANY (ARRAY['preparing'::text, 'validating_evidence'::text, 'analyzing'::text, 'synthesizing'::text, 'merging'::text, 'validating_output'::text, 'saving'::text, 'complete'::text])));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'done'::text, 'error'::text, 'cancelled'::text, 'stale'::text])));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_synthesis_done_count_check CHECK ((synthesis_done_count >= 0));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_synthesis_total_count_check CHECK ((synthesis_total_count >= 0));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_jobs_total_count_check CHECK ((total_count >= 0));
ALTER TABLE app_knowledge_jobs ADD CONSTRAINT app_knowledge_synthesis_progress_check CHECK ((synthesis_done_count <= synthesis_total_count));
ALTER TABLE app_knowledge_review_events ADD CONSTRAINT app_knowledge_review_events_action_check CHECK (((length(action) >= 1) AND (length(action) <= 80)));
ALTER TABLE app_knowledge_review_events ADD CONSTRAINT app_knowledge_review_events_details_check CHECK ((jsonb_typeof(details) = 'object'::text));
ALTER TABLE app_knowledge_review_events ADD CONSTRAINT app_knowledge_review_events_from_status_check CHECK (((from_status IS NULL) OR (from_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'approved'::text, 'superseded'::text]))));
ALTER TABLE app_knowledge_review_events ADD CONSTRAINT app_knowledge_review_events_to_status_check CHECK (((to_status IS NULL) OR (to_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'approved'::text, 'superseded'::text]))));
ALTER TABLE app_knowledge_revisions ADD CONSTRAINT app_knowledge_generated_revision_actor_check CHECK (((created_by IS NOT NULL) OR (author_type = 'generated'::text)));
ALTER TABLE app_knowledge_revisions ADD CONSTRAINT app_knowledge_revisions_author_type_check CHECK ((author_type = ANY (ARRAY['generated'::text, 'user'::text])));
ALTER TABLE app_knowledge_revisions ADD CONSTRAINT app_knowledge_revisions_content_check CHECK ((jsonb_typeof(content) = 'object'::text));
ALTER TABLE app_knowledge_revisions ADD CONSTRAINT app_knowledge_revisions_evidence_manifest_check CHECK ((jsonb_typeof(evidence_manifest) = 'array'::text));
ALTER TABLE app_knowledge_revisions ADD CONSTRAINT app_knowledge_revisions_prompt_version_check CHECK ((prompt_version > 0));
ALTER TABLE app_knowledge_revisions ADD CONSTRAINT app_knowledge_revisions_provider_model_check CHECK (((length(provider_model) >= 1) AND (length(provider_model) <= 160)));
ALTER TABLE app_knowledge_revisions ADD CONSTRAINT app_knowledge_revisions_review_status_check CHECK ((review_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'approved'::text, 'superseded'::text])));
ALTER TABLE app_knowledge_revisions ADD CONSTRAINT app_knowledge_revisions_revision_number_check CHECK ((revision_number > 0));
ALTER TABLE app_knowledge_revisions ADD CONSTRAINT app_knowledge_revisions_source_sha256_check CHECK ((source_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE app_preview_images ADD CONSTRAINT app_preview_images_rank_check CHECK (((rank >= 1) AND (rank <= 3)));
ALTER TABLE app_versions ADD CONSTRAINT app_versions_provider_check CHECK ((provider = ANY (ARRAY['m'::text, 'f'::text])));
ALTER TABLE app_versions ADD CONSTRAINT app_versions_publication_markers_consistent CHECK (((status = 'published'::text) = (published_at IS NOT NULL))) NOT VALID;
ALTER TABLE app_versions ADD CONSTRAINT app_versions_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'in_review'::text, 'published'::text, 'archived'::text])));
ALTER TABLE app_versions ADD CONSTRAINT app_versions_version_number_check CHECK ((version_number > 0));
ALTER TABLE categories ADD CONSTRAINT categories_name_check CHECK (((name = btrim(name)) AND (name <> ''::text)));
ALTER TABLE categories ADD CONSTRAINT categories_slug_check CHECK (((slug = btrim(slug)) AND (slug = lower(slug)) AND (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text)));
ALTER TABLE collection_items ADD CONSTRAINT collection_items_kind_check CHECK ((kind = ANY (ARRAY['app'::text, 'screen'::text, 'component'::text, 'token'::text, 'flow'::text, 'pattern'::text])));
ALTER TABLE crawl_account_leases ADD CONSTRAINT crawl_account_leases_purpose_check CHECK ((purpose = ANY (ARRAY['mutation'::text, 'authentication'::text])));
ALTER TABLE crawl_account_sessions ADD CONSTRAINT crawl_account_sessions_state_version_check CHECK ((state_version > 0));
ALTER TABLE crawl_dossiers ADD CONSTRAINT crawl_dossiers_dossier_check CHECK ((jsonb_typeof(dossier) = 'object'::text));
ALTER TABLE crawl_dossiers ADD CONSTRAINT crawl_dossiers_revision_check CHECK ((revision > 0));
ALTER TABLE crawl_evidence ADD CONSTRAINT crawl_evidence_viewport_height_check CHECK ((viewport_height > 0));
ALTER TABLE crawl_evidence ADD CONSTRAINT crawl_evidence_viewport_width_check CHECK ((viewport_width > 0));
ALTER TABLE crawl_missions ADD CONSTRAINT crawl_missions_mode_check CHECK ((mode = ANY (ARRAY['read'::text, 'mutate'::text])));
ALTER TABLE crawl_missions ADD CONSTRAINT crawl_missions_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'blocked'::text, 'failed'::text, 'interrupted'::text, 'cancelled'::text])));
ALTER TABLE crawl_plans ADD CONSTRAINT crawl_plans_content_hash_check CHECK ((length(content_hash) = 64));
ALTER TABLE crawl_plans ADD CONSTRAINT crawl_plans_plan_check CHECK ((jsonb_typeof(plan) = 'object'::text));
ALTER TABLE crawl_plans ADD CONSTRAINT crawl_plans_research_metadata_check CHECK ((jsonb_typeof(research_metadata) = 'object'::text));
ALTER TABLE crawl_plans ADD CONSTRAINT crawl_plans_revision_check CHECK ((revision > 0));
ALTER TABLE crawl_plans ADD CONSTRAINT crawl_plans_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'approved'::text, 'superseded'::text])));
ALTER TABLE crawl_repairs ADD CONSTRAINT crawl_repairs_failure_check CHECK ((jsonb_typeof(failure) = 'object'::text));
ALTER TABLE crawl_repairs ADD CONSTRAINT crawl_repairs_proposed_step_check CHECK ((jsonb_typeof(proposed_step) = 'object'::text));
ALTER TABLE crawl_repairs ADD CONSTRAINT crawl_repairs_status_check CHECK ((status = ANY (ARRAY['proposed'::text, 'applied'::text, 'rejected'::text])));
ALTER TABLE crawl_run_steps ADD CONSTRAINT crawl_run_steps_attempts_check CHECK ((attempts >= 0));
ALTER TABLE crawl_run_steps ADD CONSTRAINT crawl_run_steps_flow_order_check CHECK ((flow_order >= 0));
ALTER TABLE crawl_run_steps ADD CONSTRAINT crawl_run_steps_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'completed'::text, 'skipped'::text, 'failed'::text])));
ALTER TABLE crawl_run_steps ADD CONSTRAINT crawl_run_steps_step_order_check CHECK ((step_order >= 0));
ALTER TABLE crawl_runs ADD CONSTRAINT crawl_runs_completed_count_check CHECK ((completed_count >= 0));
ALTER TABLE crawl_runs ADD CONSTRAINT crawl_runs_environment_check CHECK ((jsonb_typeof(environment) = 'object'::text));
ALTER TABLE crawl_runs ADD CONSTRAINT crawl_runs_failed_count_check CHECK ((failed_count >= 0));
ALTER TABLE crawl_runs ADD CONSTRAINT crawl_runs_kind_plan_ck CHECK ((((run_kind = 'planned'::text) AND (plan_id IS NOT NULL)) OR ((run_kind = 'autonomous'::text) AND (plan_id IS NULL))));
ALTER TABLE crawl_runs ADD CONSTRAINT crawl_runs_retry_mode_check CHECK ((retry_mode = ANY (ARRAY['all'::text, 'failed'::text, 'remaining'::text])));
ALTER TABLE crawl_runs ADD CONSTRAINT crawl_runs_run_kind_check CHECK ((run_kind = ANY (ARRAY['planned'::text, 'autonomous'::text])));
ALTER TABLE crawl_runs ADD CONSTRAINT crawl_runs_skipped_count_check CHECK ((skipped_count >= 0));
ALTER TABLE crawl_runs ADD CONSTRAINT crawl_runs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text, 'interrupted'::text])));
ALTER TABLE crawl_transitions ADD CONSTRAINT crawl_transitions_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)));
ALTER TABLE crawl_transitions ADD CONSTRAINT crawl_transitions_mode_check CHECK ((mode = ANY (ARRAY['read'::text, 'mutate'::text])));
ALTER TABLE crawl_transitions ADD CONSTRAINT crawl_transitions_outcome_check CHECK ((outcome = ANY (ARRAY['completed'::text, 'failed'::text, 'blocked'::text])));
ALTER TABLE design_system_import_history ADD CONSTRAINT design_system_import_history_previous_origin_check CHECK ((previous_origin = ANY (ARRAY['observed'::text, 'imported'::text])));
ALTER TABLE design_system_import_history ADD CONSTRAINT design_system_import_history_source_hash_check CHECK ((source_hash ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE design_systems ADD CONSTRAINT design_systems_origin_check CHECK ((origin = ANY (ARRAY['observed'::text, 'automatic'::text, 'imported'::text])));
ALTER TABLE export_usage ADD CONSTRAINT export_usage_operation_count_check CHECK ((operation_count >= 0));
ALTER TABLE exports ADD CONSTRAINT exports_status_check CHECK ((status = ANY (ARRAY['generating'::text, 'complete'::text, 'failed'::text])));
ALTER TABLE external_design_systems ADD CONSTRAINT external_design_systems_content_hash_check CHECK ((content_hash ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE external_design_systems ADD CONSTRAINT external_design_systems_raw_payload_check CHECK ((jsonb_typeof(raw_payload) = 'object'::text));
ALTER TABLE external_design_systems ADD CONSTRAINT external_design_systems_snapshot_check CHECK ((jsonb_typeof(snapshot) = 'object'::text));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_check CHECK ((done_count <= total_count));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_check1 CHECK (((error_code IS NULL) OR (status = ANY (ARRAY['error'::text, 'stale'::text]))));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_done_count_check CHECK ((done_count >= 0));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_evidence_manifest_check CHECK ((jsonb_typeof(evidence_manifest) = 'array'::text));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_evidence_manifest_sha256_check CHECK ((evidence_manifest_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_focus_instruction_check CHECK ((char_length(focus_instruction) <= 2000));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_prompt_version_check CHECK ((prompt_version > 0));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_provider_model_check CHECK (((char_length(provider_model) >= 1) AND (char_length(provider_model) <= 160)));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_source_flow_check CHECK ((jsonb_typeof(source_flow) = 'object'::text));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_stage_check CHECK ((stage = ANY (ARRAY['preparing'::text, 'analyzing'::text, 'synthesizing'::text, 'validating'::text, 'saving'::text, 'complete'::text])));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'done'::text, 'error'::text, 'cancelled'::text, 'stale'::text])));
ALTER TABLE feature_document_jobs ADD CONSTRAINT feature_document_jobs_total_count_check CHECK ((total_count > 0));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_author_type_check CHECK ((author_type = ANY (ARRAY['generated'::text, 'user'::text, 'restored'::text])));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_content_check CHECK ((jsonb_typeof(content) = 'object'::text));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_evidence_manifest_check CHECK ((jsonb_typeof(evidence_manifest) = 'array'::text));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_evidence_manifest_sha256_check CHECK ((evidence_manifest_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_focus_instruction_check CHECK ((char_length(focus_instruction) <= 2000));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_prompt_version_check CHECK ((prompt_version > 0));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_provider_model_check CHECK (((char_length(provider_model) >= 1) AND (char_length(provider_model) <= 160)));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_review_status_check CHECK ((review_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'approved'::text, 'superseded'::text])));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_revision_number_check CHECK ((revision_number > 0));
ALTER TABLE feature_document_revisions ADD CONSTRAINT feature_document_revisions_source_flow_check CHECK ((jsonb_typeof(source_flow) = 'object'::text));
ALTER TABLE feature_document_shares ADD CONSTRAINT feature_document_shares_check CHECK ((expires_at > created_at));
ALTER TABLE feature_document_shares ADD CONSTRAINT feature_document_shares_token_sha256_check CHECK ((token_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE feature_document_step_analyses ADD CONSTRAINT feature_document_step_analyses_attempt_count_check CHECK (((attempt_count >= 1) AND (attempt_count <= 3)));
ALTER TABLE feature_document_step_analyses ADD CONSTRAINT feature_document_step_analyses_check CHECK ((((status = 'complete'::text) AND (result IS NOT NULL) AND (error_code IS NULL)) OR ((status = 'failed'::text) AND (result IS NULL) AND (error_code IS NOT NULL))));
ALTER TABLE feature_document_step_analyses ADD CONSTRAINT feature_document_step_analyses_evidence_id_check CHECK (((char_length(evidence_id) >= 1) AND (char_length(evidence_id) <= 240)));
ALTER TABLE feature_document_step_analyses ADD CONSTRAINT feature_document_step_analyses_image_index_check CHECK ((image_index >= 0));
ALTER TABLE feature_document_step_analyses ADD CONSTRAINT feature_document_step_analyses_status_check CHECK ((status = ANY (ARRAY['complete'::text, 'failed'::text])));
ALTER TABLE feature_document_step_analyses ADD CONSTRAINT feature_document_step_analyses_step_index_check CHECK ((step_index >= 0));
ALTER TABLE feature_documents ADD CONSTRAINT feature_documents_source_change_acknowledged_sha256_check CHECK (((source_change_acknowledged_sha256 IS NULL) OR (source_change_acknowledged_sha256 ~ '^[0-9a-f]{64}$'::text)));
ALTER TABLE feature_documents ADD CONSTRAINT feature_documents_source_flow_id_check CHECK (((char_length(source_flow_id) >= 1) AND (char_length(source_flow_id) <= 240)));
ALTER TABLE feature_documents ADD CONSTRAINT feature_documents_title_check CHECK (((char_length(title) >= 1) AND (char_length(title) <= 160)));
ALTER TABLE feature_documents ADD CONSTRAINT feature_documents_visibility_check CHECK ((visibility = ANY (ARRAY['private'::text, 'catalog'::text])));
ALTER TABLE flows ADD CONSTRAINT flows_check CHECK (((parent_id IS NULL) OR (parent_id <> id)));
ALTER TABLE flows ADD CONSTRAINT flows_name_check CHECK ((btrim(name) <> ''::text));
ALTER TABLE flows ADD CONSTRAINT flows_normalized_name_check CHECK ((btrim(normalized_name) <> ''::text));
ALTER TABLE media_migration_state ADD CONSTRAINT media_migration_state_attempts_check CHECK ((attempts >= 0));
ALTER TABLE media_migration_state ADD CONSTRAINT media_migration_state_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'complete'::text, 'failed'::text])));
ALTER TABLE organization_members ADD CONSTRAINT organization_members_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])));
ALTER TABLE project_document_collaborators ADD CONSTRAINT project_document_collaborators_role_check CHECK ((role = ANY (ARRAY['editor'::text, 'viewer'::text])));
ALTER TABLE project_document_collections ADD CONSTRAINT project_document_collections_mode_check CHECK ((mode = ANY (ARRAY['manual'::text, 'rules'::text])));
ALTER TABLE project_document_collections ADD CONSTRAINT project_document_collections_name_check CHECK (((char_length(name) >= 1) AND (char_length(name) <= 80)));
ALTER TABLE project_document_collections ADD CONSTRAINT project_document_collections_rules_check CHECK ((jsonb_typeof(rules) = 'array'::text));
ALTER TABLE project_document_comments ADD CONSTRAINT project_document_comments_anchor_shape CHECK (((quote IS NULL) OR (block_id IS NOT NULL)));
ALTER TABLE project_document_comments ADD CONSTRAINT project_document_comments_block_id_length CHECK (((block_id IS NULL) OR ((char_length(block_id) >= 1) AND (char_length(block_id) <= 200))));
ALTER TABLE project_document_comments ADD CONSTRAINT project_document_comments_body_length CHECK (((char_length(body) >= 1) AND (char_length(body) <= 2000)));
ALTER TABLE project_document_comments ADD CONSTRAINT project_document_comments_parent_not_self CHECK (((parent_comment_id IS NULL) OR (parent_comment_id <> id)));
ALTER TABLE project_document_comments ADD CONSTRAINT project_document_comments_quote_length CHECK (((quote IS NULL) OR ((char_length(quote) >= 1) AND (char_length(quote) <= 500))));
ALTER TABLE project_document_folders ADD CONSTRAINT project_document_folders_check CHECK (((parent_folder_id IS NULL) OR (parent_folder_id <> id)));
ALTER TABLE project_document_folders ADD CONSTRAINT project_document_folders_name_check CHECK (((char_length(name) >= 1) AND (char_length(name) <= 80)));
ALTER TABLE project_document_links ADD CONSTRAINT project_document_links_no_self_link CHECK ((source_document_id <> target_document_id));
ALTER TABLE project_document_realtime_states ADD CONSTRAINT project_document_realtime_states_size CHECK ((((byte_size >= 1) AND (byte_size <= 8388608)) AND (octet_length(state) = byte_size)));
ALTER TABLE project_document_shares ADD CONSTRAINT project_document_shares_token_sha256_check CHECK ((token_sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE project_document_tags ADD CONSTRAINT project_document_tags_color_check CHECK ((color = ANY (ARRAY['blue'::text, 'purple'::text, 'green'::text, 'amber'::text, 'rose'::text, 'slate'::text])));
ALTER TABLE project_document_tags ADD CONSTRAINT project_document_tags_name_check CHECK (((char_length(name) >= 1) AND (char_length(name) <= 80)));
ALTER TABLE project_document_versions ADD CONSTRAINT project_document_versions_label_length CHECK (((char_length((label)::text) >= 1) AND (char_length((label)::text) <= 120)));
ALTER TABLE project_document_versions ADD CONSTRAINT project_document_versions_snapshot_size CHECK ((((byte_size >= 1) AND (byte_size <= 8388608)) AND (octet_length(snapshot) = byte_size)));
ALTER TABLE project_documents ADD CONSTRAINT project_documents_attribution_email_length CHECK ((((char_length(created_by_email) >= 1) AND (char_length(created_by_email) <= 320)) AND ((char_length(last_edited_by_email) >= 1) AND (char_length(last_edited_by_email) <= 320))));
ALTER TABLE project_documents ADD CONSTRAINT project_documents_icon_check CHECK ((icon = ANY (ARRAY['none'::text, 'document'::text, 'idea'::text, 'task'::text, 'schedule'::text, 'build'::text])));
ALTER TABLE project_documents ADD CONSTRAINT project_documents_last_editor_mode_check CHECK ((last_editor_mode = ANY (ARRAY['page'::text, 'edgeless'::text])));
ALTER TABLE project_documents ADD CONSTRAINT project_documents_page_width_check CHECK ((page_width = ANY (ARRAY['standard'::text, 'full'::text])));
ALTER TABLE project_documents ADD CONSTRAINT project_documents_properties_array CHECK ((jsonb_typeof(properties) = 'array'::text));
ALTER TABLE project_documents ADD CONSTRAINT project_documents_properties_limit CHECK ((jsonb_array_length(properties) <= 50));
ALTER TABLE project_documents ADD CONSTRAINT project_documents_search_text_length CHECK ((char_length(search_text) <= 200000));
ALTER TABLE project_documents ADD CONSTRAINT project_documents_template_snapshot CHECK ((((is_template = false) AND (template_snapshot IS NULL)) OR ((is_template = true) AND ((octet_length(template_snapshot) >= 1) AND (octet_length(template_snapshot) <= 8388608)))));
ALTER TABLE promotional_entitlements ADD CONSTRAINT promotional_entitlements_check CHECK ((expires_at > starts_at));
ALTER TABLE promotional_entitlements ADD CONSTRAINT promotional_entitlements_source_check CHECK ((source = ANY (ARRAY['referral_signup'::text, 'referral_reward'::text])));
ALTER TABLE public_facet_previews ADD CONSTRAINT public_facet_previews_facet_group_check CHECK ((facet_group = ANY (ARRAY['screens'::text, 'elements'::text, 'flows'::text])));
ALTER TABLE public_facet_previews ADD CONSTRAINT public_facet_previews_rank_check CHECK (((rank >= 1) AND (rank <= 3)));
ALTER TABLE referral_activity ADD CONSTRAINT referral_activity_check CHECK ((last_opened_at >= first_opened_at));
ALTER TABLE referral_codes ADD CONSTRAINT referral_codes_token_check CHECK (((length(token) >= 32) AND (length(token) <= 128)));
ALTER TABLE referral_rewards ADD CONSTRAINT referral_rewards_check CHECK ((((state = 'available'::text) AND (entitlement_id IS NULL) AND (activated_at IS NULL) AND (revoked_at IS NULL)) OR ((state = 'activated'::text) AND (entitlement_id IS NOT NULL) AND (activated_at IS NOT NULL) AND (revoked_at IS NULL)) OR ((state = 'revoked'::text) AND (revoked_at IS NOT NULL))));
ALTER TABLE referral_rewards ADD CONSTRAINT referral_rewards_state_check CHECK ((state = ANY (ARRAY['available'::text, 'activated'::text, 'revoked'::text])));
ALTER TABLE referrals ADD CONSTRAINT referrals_check CHECK ((inviter_user_id <> invited_user_id));
ALTER TABLE research_project_canvas_assets ADD CONSTRAINT research_project_canvas_assets_asset_id_check CHECK (((char_length(asset_id) >= 7) AND (char_length(asset_id) <= 240)));
ALTER TABLE research_project_canvas_files ADD CONSTRAINT research_project_canvas_files_revision_check CHECK ((revision > 0));
ALTER TABLE research_project_canvas_files ADD CONSTRAINT research_project_canvas_files_snapshot_check CHECK ((jsonb_typeof(snapshot) = 'object'::text));
ALTER TABLE research_project_canvas_files ADD CONSTRAINT research_project_canvas_files_title_check CHECK (((char_length(title) >= 1) AND (char_length(title) <= 120)));
ALTER TABLE research_project_canvases ADD CONSTRAINT research_project_canvases_revision_check CHECK ((revision > 0));
ALTER TABLE research_project_canvases ADD CONSTRAINT research_project_canvases_snapshot_check CHECK ((jsonb_typeof(snapshot) = 'object'::text));
ALTER TABLE research_project_items ADD CONSTRAINT research_project_items_catalog_step_index_check CHECK (((catalog_step_index IS NULL) OR (catalog_step_index >= 0)));
ALTER TABLE research_project_items ADD CONSTRAINT research_project_items_check CHECK ((((source_kind = 'private_upload'::text) AND (private_object_key IS NOT NULL) AND (catalog_app IS NULL)) OR ((source_kind <> 'private_upload'::text) AND (private_object_key IS NULL) AND (catalog_app IS NOT NULL))));
ALTER TABLE research_project_items ADD CONSTRAINT research_project_items_note_check CHECK ((char_length(note) <= 4000));
ALTER TABLE research_project_items ADD CONSTRAINT research_project_items_position_check CHECK ((("position" >= 0) AND ("position" <= 99)));
ALTER TABLE research_project_items ADD CONSTRAINT research_project_items_source_kind_check CHECK ((source_kind = ANY (ARRAY['catalog_screen'::text, 'catalog_flow_step'::text, 'private_upload'::text])));
ALTER TABLE research_project_items ADD CONSTRAINT research_project_items_source_snapshot_check CHECK ((jsonb_typeof(source_snapshot) = 'object'::text));
ALTER TABLE research_project_items ADD CONSTRAINT research_project_items_step_label_check CHECK ((char_length(step_label) <= 240));
ALTER TABLE research_project_items ADD CONSTRAINT research_project_items_tags_check CHECK ((jsonb_typeof(tags) = 'array'::text));
ALTER TABLE research_project_lanes ADD CONSTRAINT research_project_lanes_conclusion_check CHECK ((char_length(conclusion) <= 4000));
ALTER TABLE research_project_lanes ADD CONSTRAINT research_project_lanes_position_check CHECK ((("position" >= 0) AND ("position" <= 4)));
ALTER TABLE research_project_lanes ADD CONSTRAINT research_project_lanes_title_check CHECK (((char_length(title) >= 1) AND (char_length(title) <= 120)));
ALTER TABLE research_project_syntheses ADD CONSTRAINT research_project_syntheses_check CHECK ((((status = 'complete'::text) AND (result IS NOT NULL) AND (error_code IS NULL)) OR ((status = 'failed'::text) AND (result IS NULL) AND (error_code IS NOT NULL))));
ALTER TABLE research_project_syntheses ADD CONSTRAINT research_project_syntheses_project_revision_check CHECK ((project_revision > 0));
ALTER TABLE research_project_syntheses ADD CONSTRAINT research_project_syntheses_schema_version_check CHECK ((schema_version > 0));
ALTER TABLE research_project_syntheses ADD CONSTRAINT research_project_syntheses_status_check CHECK ((status = ANY (ARRAY['complete'::text, 'failed'::text])));
ALTER TABLE research_projects ADD CONSTRAINT research_projects_constraints_check CHECK ((char_length(constraints) <= 4000));
ALTER TABLE research_projects ADD CONSTRAINT research_projects_decision_check CHECK ((char_length(decision) <= 8000));
ALTER TABLE research_projects ADD CONSTRAINT research_projects_icon_check CHECK ((icon = ANY (ARRAY['initial'::text, 'folder'::text, 'grid'::text, 'book'::text, 'sparkle'::text])));
ALTER TABLE research_projects ADD CONSTRAINT research_projects_open_questions_check CHECK ((char_length(open_questions) <= 4000));
ALTER TABLE research_projects ADD CONSTRAINT research_projects_platform_filter_check CHECK ((platform_filter = ANY (ARRAY['all'::text, 'ios'::text, 'android'::text, 'web'::text])));
ALTER TABLE research_projects ADD CONSTRAINT research_projects_question_check CHECK ((char_length(question) <= 1000));
ALTER TABLE research_projects ADD CONSTRAINT research_projects_rationale_check CHECK ((char_length(rationale) <= 8000));
ALTER TABLE research_projects ADD CONSTRAINT research_projects_revision_check CHECK ((revision > 0));
ALTER TABLE research_projects ADD CONSTRAINT research_projects_title_check CHECK (((char_length(title) >= 1) AND (char_length(title) <= 120)));
ALTER TABLE review_issues ADD CONSTRAINT review_issues_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'warning'::text, 'blocker'::text])));
ALTER TABLE screen_pattern_assignments ADD CONSTRAINT screen_pattern_assignments_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)));
ALTER TABLE screen_pattern_assignments ADD CONSTRAINT screen_pattern_assignments_source_check CHECK ((source = ANY (ARRAY['analysis'::text, 'imported'::text, 'manual'::text])));
ALTER TABLE screen_pattern_sections ADD CONSTRAINT screen_pattern_sections_name_check CHECK (((length(name) >= 1) AND (length(name) <= 120)));
ALTER TABLE screen_pattern_sections ADD CONSTRAINT screen_pattern_sections_position_check CHECK (("position" > 0));
ALTER TABLE screen_pattern_sections ADD CONSTRAINT screen_pattern_sections_slug_check CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text));
ALTER TABLE screen_patterns ADD CONSTRAINT screen_patterns_description_check CHECK (((length(description) >= 1) AND (length(description) <= 1000)));
ALTER TABLE screen_patterns ADD CONSTRAINT screen_patterns_name_check CHECK (((length(name) >= 1) AND (length(name) <= 160)));
ALTER TABLE screen_patterns ADD CONSTRAINT screen_patterns_position_check CHECK (("position" > 0));
ALTER TABLE screen_patterns ADD CONSTRAINT screen_patterns_slug_check CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_check CHECK (((region_x + region_width) <= (1)::double precision));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_check1 CHECK (((region_y + region_height) <= (1)::double precision));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_crop_quality_object CHECK (((crop_quality IS NULL) OR (jsonb_typeof(crop_quality) = 'object'::text)));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_prompt_version_check CHECK ((prompt_version > 0));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_provider_model_check CHECK (((length(provider_model) >= 1) AND (length(provider_model) <= 160)));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_purpose_check CHECK (((length(purpose) >= 1) AND (length(purpose) <= 1000)));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_region_height_check CHECK (((region_height > (0)::double precision) AND (region_height <= (1)::double precision)));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_region_width_check CHECK (((region_width > (0)::double precision) AND (region_width <= (1)::double precision)));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_region_x_check CHECK (((region_x >= (0)::double precision) AND (region_x <= (1)::double precision)));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_region_y_check CHECK (((region_y >= (0)::double precision) AND (region_y <= (1)::double precision)));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_review_status_check CHECK ((review_status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])));
ALTER TABLE screen_ui_elements ADD CONSTRAINT screen_ui_elements_variant_check CHECK (((length(variant) >= 1) AND (length(variant) <= 160)));
ALTER TABLE site_pages ADD CONSTRAINT site_pages_position_check CHECK (("position" >= 0));
ALTER TABLE site_sections ADD CONSTRAINT site_sections_media_kind_check CHECK ((media_kind = ANY (ARRAY['image'::text, 'video'::text])));
ALTER TABLE site_sections ADD CONSTRAINT site_sections_media_metadata_check CHECK ((((media_kind = 'image'::text) AND (video_start_seconds IS NULL) AND (video_end_seconds IS NULL) AND (((crop_top IS NULL) AND (crop_bottom IS NULL)) OR ((crop_top IS NOT NULL) AND (crop_bottom IS NOT NULL) AND (crop_top >= (0)::double precision) AND (crop_bottom > crop_top)))) OR ((media_kind = 'video'::text) AND (crop_top IS NULL) AND (crop_bottom IS NULL) AND (((video_start_seconds IS NULL) AND (video_end_seconds IS NULL)) OR ((video_start_seconds IS NOT NULL) AND (video_end_seconds IS NOT NULL) AND (video_start_seconds >= (0)::double precision) AND (video_end_seconds > video_start_seconds))))));
ALTER TABLE site_sections ADD CONSTRAINT site_sections_ocr_boxes_check CHECK ((jsonb_typeof(ocr_boxes) = 'array'::text));
ALTER TABLE site_sections ADD CONSTRAINT site_sections_position_check CHECK (("position" >= 0));
ALTER TABLE site_sections ADD CONSTRAINT site_sections_source_metadata_check CHECK ((jsonb_typeof(source_metadata) = 'object'::text));
ALTER TABLE site_versions ADD CONSTRAINT site_versions_analysis_check CHECK ((jsonb_typeof(analysis) = 'object'::text));
ALTER TABLE site_versions ADD CONSTRAINT site_versions_analysis_status_check CHECK ((analysis_status = ANY (ARRAY['ready'::text, 'evidence-only'::text])));
ALTER TABLE site_versions ADD CONSTRAINT site_versions_catalog_snapshot_check CHECK ((jsonb_typeof(catalog_snapshot) = 'object'::text));
ALTER TABLE site_versions ADD CONSTRAINT site_versions_catalog_snapshot_complete CHECK (((catalog_snapshot <> '{}'::jsonb) AND (catalog_snapshot ?& ARRAY['name'::text, 'slug'::text, 'sourceUrl'::text, 'description'::text, 'logoUrl'::text, 'categories'::text, 'categoriesNormalized'::text, 'styles'::text, 'stylesNormalized'::text, 'popularity'::text]) AND (jsonb_typeof((catalog_snapshot -> 'name'::text)) = 'string'::text) AND (jsonb_typeof((catalog_snapshot -> 'slug'::text)) = 'string'::text) AND (jsonb_typeof((catalog_snapshot -> 'sourceUrl'::text)) = 'string'::text) AND ((jsonb_typeof((catalog_snapshot -> 'description'::text)) = 'string'::text) OR ((catalog_snapshot -> 'description'::text) = 'null'::jsonb)) AND ((jsonb_typeof((catalog_snapshot -> 'logoUrl'::text)) = 'string'::text) OR ((catalog_snapshot -> 'logoUrl'::text) = 'null'::jsonb)) AND (jsonb_typeof((catalog_snapshot -> 'categories'::text)) = 'array'::text) AND (jsonb_typeof((catalog_snapshot -> 'categoriesNormalized'::text)) = 'array'::text) AND (jsonb_typeof((catalog_snapshot -> 'styles'::text)) = 'array'::text) AND (jsonb_typeof((catalog_snapshot -> 'stylesNormalized'::text)) = 'array'::text) AND (jsonb_typeof((catalog_snapshot -> 'popularity'::text)) = 'number'::text) AND (((catalog_snapshot ->> 'popularity'::text))::numeric >= (0)::numeric)));
ALTER TABLE site_versions ADD CONSTRAINT site_versions_content_hash_check CHECK (((content_hash IS NULL) OR (content_hash ~ '^[0-9a-f]{64}$'::text)));
ALTER TABLE site_versions ADD CONSTRAINT site_versions_status_check CHECK ((status = ANY (ARRAY['importing'::text, 'ready'::text, 'failed'::text])));
ALTER TABLE sites ADD CONSTRAINT sites_categories_check CHECK ((jsonb_typeof(categories) = 'array'::text));
ALTER TABLE sites ADD CONSTRAINT sites_popularity_check CHECK ((popularity >= 0));
ALTER TABLE sites ADD CONSTRAINT sites_source_kind_check CHECK ((source_kind = ANY (ARRAY['mobbin'::text, 'public-page'::text])));
ALTER TABLE sites ADD CONSTRAINT sites_styles_check CHECK ((jsonb_typeof(styles) = 'array'::text));
ALTER TABLE stored_objects ADD CONSTRAINT stored_objects_access_class_check CHECK ((access_class = ANY (ARRAY['protected'::text, 'public-preview'::text, 'internal'::text])));
ALTER TABLE stored_objects ADD CONSTRAINT stored_objects_byte_size_check CHECK ((byte_size > 0));
ALTER TABLE stored_objects ADD CONSTRAINT stored_objects_content_type_check CHECK ((content_type = ANY (ARRAY['image/png'::text, 'image/jpeg'::text, 'image/webp'::text, 'video/mp4'::text, 'video/webm'::text, 'application/json'::text, 'application/zip'::text, 'text/css'::text, 'text/javascript'::text, 'text/typescript'::text, 'text/markdown'::text])));
ALTER TABLE stored_objects ADD CONSTRAINT stored_objects_object_key_check CHECK ((((length(object_key) >= 1) AND (length(object_key) <= 1024)) AND (object_key ~ '^[a-z0-9][a-z0-9/_=.@-]*$'::text) AND ("right"(object_key, 1) <> '/'::text) AND (POSITION(('//'::text) IN (object_key)) = 0) AND (object_key !~ '(^|/)\.{1,2}(/|$)'::text)));
ALTER TABLE stored_objects ADD CONSTRAINT stored_objects_sha256_check CHECK ((sha256 ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE subscriptions ADD CONSTRAINT subscriptions_billing_interval_check CHECK ((billing_interval = ANY (ARRAY['month'::text, 'year'::text])));
ALTER TABLE subscriptions ADD CONSTRAINT subscriptions_status_check CHECK ((status = ANY (ARRAY['incomplete'::text, 'incomplete_expired'::text, 'active'::text, 'past_due'::text, 'canceled'::text, 'unpaid'::text, 'paused'::text])));
ALTER TABLE ui_element_extractions ADD CONSTRAINT ui_element_extractions_component_count_check CHECK ((component_count >= 0));
ALTER TABLE ui_element_extractions ADD CONSTRAINT ui_element_extractions_prompt_version_check CHECK ((prompt_version > 0));
ALTER TABLE ui_element_extractions ADD CONSTRAINT ui_element_extractions_provider_model_check CHECK (((length(provider_model) >= 1) AND (length(provider_model) <= 160)));
ALTER TABLE ui_element_extractions ADD CONSTRAINT ui_element_extractions_status_check CHECK ((status = ANY (ARRAY['running'::text, 'complete'::text, 'failed'::text])));
ALTER TABLE ui_element_types ADD CONSTRAINT ui_element_types_group_name_check CHECK ((group_name = ANY (ARRAY['Control'::text, 'View'::text, 'Overlay'::text, 'Imagery'::text])));
ALTER TABLE ui_element_types ADD CONSTRAINT ui_element_types_name_check CHECK (((length(name) >= 1) AND (length(name) <= 120)));
ALTER TABLE ui_element_types ADD CONSTRAINT ui_element_types_slug_check CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text));
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'user'::text])));
ALTER TABLE web_page_sections ADD CONSTRAINT web_page_sections_height_check CHECK ((height > (0)::double precision));
ALTER TABLE web_page_sections ADD CONSTRAINT web_page_sections_position_check CHECK (("position" >= 0));
ALTER TABLE web_page_sections ADD CONSTRAINT web_page_sections_source_metadata_check CHECK ((jsonb_typeof(source_metadata) = 'object'::text));
ALTER TABLE web_page_sections ADD CONSTRAINT web_page_sections_width_check CHECK ((width > (0)::double precision));
ALTER TABLE web_page_sections ADD CONSTRAINT web_page_sections_x_check CHECK ((x >= (0)::double precision));
ALTER TABLE web_page_sections ADD CONSTRAINT web_page_sections_y_check CHECK ((y >= (0)::double precision));
ALTER TABLE web_page_versions ADD CONSTRAINT web_page_versions_content_hash_check CHECK ((content_hash ~ '^[0-9a-f]{64}$'::text));
ALTER TABLE web_page_versions ADD CONSTRAINT web_page_versions_status_check CHECK ((status = ANY (ARRAY['importing'::text, 'ready'::text, 'failed'::text])));
ALTER TABLE web_page_versions ADD CONSTRAINT web_page_versions_viewport_height_check CHECK ((viewport_height > 0));
ALTER TABLE web_page_versions ADD CONSTRAINT web_page_versions_viewport_width_check CHECK ((viewport_width > 0));
