import { useEffect, useState } from 'react';
import type { DesignSystemSnapshot, EvidenceView } from '../../designSystem';
import type { CuratorAction } from '../../curatorReview';
import type { Platform } from '../../platformFromUrl';
import { applyReviewAction } from '../researchApi';
import { loadDesignSystem } from '../useDesignSystem';

export function CuratorReviewPanel({ app, platform, snapshot }: { app: string; platform: Platform; snapshot: DesignSystemSnapshot<EvidenceView> | null }) {
  const [working, setWorking] = useState(snapshot);
  const [message, setMessage] = useState('');
  useEffect(() => setWorking(snapshot), [snapshot]);
  if (!working) return <p>No working design system to review.</p>;
  const act = async (action: CuratorAction) => { try { await applyReviewAction(app, platform, action); setWorking(await loadDesignSystem(app, platform)); setMessage('Saved without changing evidence links.'); } catch (error) { setMessage((error as Error).message); } };
  const rename = (kind: 'token' | 'component' | 'variant' | 'rule', id: string, current: string, componentId?: string) => { const name = window.prompt('Reviewed name', current)?.trim(); if (name) void act({ type: 'rename', kind, id, name, componentId }); };
  const reject = (kind: 'token' | 'component' | 'variant' | 'rule', id: string, componentId?: string) => { if (window.confirm('Reject this extracted item? Its source screen remains in the version.')) void act({ type: 'reject', kind, id, componentId }); };
  const merge = () => { const ids = window.prompt('Component ids to merge, comma separated')?.split(',').map((value) => value.trim()).filter(Boolean); if (!ids || ids.length < 2) return; const targetId = window.prompt('Merged component id', ids[0])?.trim(); const name = window.prompt('Merged component name')?.trim(); if (targetId && name) void act({ type: 'merge-components', ids, targetId, name }); };
  const split = (id: string) => { const variantIds = window.prompt('Variant ids to move, comma separated')?.split(',').map((value) => value.trim()).filter(Boolean); const newId = window.prompt('New component id')?.trim(); const name = window.prompt('New component name')?.trim(); if (variantIds?.length && newId && name) void act({ type: 'split-component', id, variantIds, newId, name }); };
  return <div style={{ display: 'grid', gap: 22, paddingTop: 28 }}><div><h2 style={{ margin: 0 }}>Curator review</h2><p style={{ color: 'var(--color-text-secondary)' }}>Rename, reject, merge, or split extracted entities. These actions preserve captured screens and retained evidence IDs.</p></div><section><h3>Foundation tokens</h3>{working.tokens.map((token) => <div key={token.id} style={rowStyle}><span style={{ flex: 1 }}><strong>{token.name}</strong> · {token.id} · {token.evidence.length} sources</span><button onClick={() => rename('token', token.id, token.name)} style={buttonStyle}>Rename</button><button onClick={() => reject('token', token.id)} style={buttonStyle}>Reject</button></div>)}</section><section><div style={{ display: 'flex', alignItems: 'center' }}><h3 style={{ flex: 1 }}>Components and variants</h3><button onClick={merge} style={buttonStyle}>Merge components</button></div>{working.components.map((component) => <div key={component.id} style={{ ...rowStyle, display: 'block' }}><div style={{ display: 'flex', gap: 7 }}><span style={{ flex: 1 }}><strong>{component.name}</strong> · {component.id}</span><button onClick={() => rename('component', component.id, component.name)} style={buttonStyle}>Rename</button><button onClick={() => split(component.id)} style={buttonStyle}>Split</button><button onClick={() => reject('component', component.id)} style={buttonStyle}>Reject</button></div>{component.variants.map((variant) => <div key={variant.id} style={{ display: 'flex', gap: 7, marginTop: 8, paddingLeft: 16, fontSize: 12 }}><span style={{ flex: 1 }}>{variant.name} · {variant.id} · evidence {variant.evidence.map((item) => item.imageId).join(', ')}</span><button onClick={() => rename('variant', variant.id, variant.name, component.id)} style={buttonStyle}>Rename</button><button onClick={() => reject('variant', variant.id, component.id)} style={buttonStyle}>Reject</button></div>)}</div>)}</section>{message && <div role="status">{message}</div>}</div>;
}
const rowStyle = { display: 'flex', gap: 7, alignItems: 'center', padding: 10, marginTop: 7, border: '1px solid var(--color-border)', borderRadius: 9, fontSize: 12.5 };
const buttonStyle = { border: '1px solid var(--color-border)', borderRadius: 7, padding: '5px 8px', background: 'var(--color-background-surface)', color: 'var(--color-text-primary)', cursor: 'pointer', font: 'inherit', fontSize: 11 };
